/******************************************************************************\
 *** 
 *** Simulink model       : applbev_EVCU2
 *** TargetLink subsystem : applbev_EVCU2/ApplicationLayerBEV_ac
 *** Codefile             : ApplBev_Output.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2024-02-19 12:59:58
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : AUTOSAR
 *** AUTOSAR version                          : 4.0.3
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : disabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : enabled
 *** Exploit ranges if not erasable           : enabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : unlimited
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : disabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : disabled
 *** Inlining Threshold                       : 10
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : disabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : D:\users\valsania\Desktop\Proget
 ***                                            ti\EVCU2_Work\SWC\0AF_2402\EVCU2
 ***                                            _SWC_APPLBEV\MDL\applbev_s_prj\a
 ***                                            pplbev_c_prj\config\cconfig_AR.x
 ***                                            ml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLi
 ***                                            nk 4.3\Matlab\Tl\XML\CodeGen\Sty
 ***                                            lesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 4.3p5 from 18-Sep-2019
 *** Code generator version  : Build Id 4.3.0.29 from 2019-09-19 11:35:24
 *** Copyright (c) 2012 dSPACE GmbH\****************************************************************
 **************/

#ifndef APPLBEV_OUTPUT_H
#define APPLBEV_OUTPUT_H

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "Rte_Type.h"
#include "tl_defines_a.h"

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

extern MERGEABLE_CAL_PRAGMA float32 ACC_Wheel_Torque_phyconv_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 NvMout_BEV_TireTol_Ratio_FL_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 NvMout_BEV_TireTol_Ratio_FR_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 NvMout_BEV_TireTol_Ratio_RL_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 NvMout_BEV_TireTol_Ratio_RR_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 NvMout_BEV_TireTol_Stiffness_FL_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 NvMout_BEV_TireTol_Stiffness_FR_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 NvMout_BEV_TireTol_Stiffness_RL_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 NvMout_BEV_TireTol_Stiffness_RR_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 NvMout_BEV_TireTol_p11_FL_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 NvMout_BEV_TireTol_p11_FR_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 NvMout_BEV_TireTol_p11_RL_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 NvMout_BEV_TireTol_p11_RR_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eAWD_SplitFactor_Minus_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eAWD_SplitFactor_Plus_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eDTC_OL_TrqMinF_Nm_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eDTC_OL_TrqMinR_Nm_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_ACC_Wheel_Torque_phyconv_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_ACC_Wheel_Torque_phyconv_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_ACC_Wheel_Torque_phyconv_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_ACC_Wheel_Torque_phyconv_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_ACC_Wheel_Torque_phyconv_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Ratio_FL_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Ratio_FL_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Ratio_FL_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Ratio_FL_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Ratio_FL_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Ratio_FR_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Ratio_FR_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Ratio_FR_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Ratio_FR_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Ratio_FR_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Ratio_RL_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Ratio_RL_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Ratio_RL_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Ratio_RL_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Ratio_RL_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Ratio_RR_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Ratio_RR_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Ratio_RR_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Ratio_RR_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Ratio_RR_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Stiffness_FL_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Stiffness_FL_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Stiffness_FL_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Stiffness_FL_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Stiffness_FL_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Stiffness_FR_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Stiffness_FR_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Stiffness_FR_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Stiffness_FR_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Stiffness_FR_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Stiffness_RL_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Stiffness_RL_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Stiffness_RL_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Stiffness_RL_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Stiffness_RL_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Stiffness_RR_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Stiffness_RR_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Stiffness_RR_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Stiffness_RR_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_Stiffness_RR_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_p11_FL_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_p11_FL_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_p11_FL_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_p11_FL_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_p11_FL_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_p11_FR_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_p11_FR_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_p11_FR_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_p11_FR_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_p11_FR_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_p11_RL_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_p11_RL_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_p11_RL_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_p11_RL_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_p11_RL_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_p11_RR_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_p11_RR_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_p11_RR_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_p11_RR_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_NvMout_BEV_TireTol_p11_RR_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_RELSD_TgtTrq_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_RELSD_TgtTrq_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_RELSD_TgtTrq_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_RELSD_TgtTrq_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_RELSD_TgtTrq_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eAWD_IntvActv_b_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eAWD_IntvActv_b_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eAWD_IntvActv_b_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eAWD_IntvActv_b_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eAWD_IntvActv_b_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eAWD_SplitFactor_Minus_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eAWD_SplitFactor_Minus_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eAWD_SplitFactor_Minus_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eAWD_SplitFactor_Minus_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eAWD_SplitFactor_Minus_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eAWD_SplitFactor_Plus_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eAWD_SplitFactor_Plus_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eAWD_SplitFactor_Plus_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eAWD_SplitFactor_Plus_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eAWD_SplitFactor_Plus_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eDTC_OL_TrqMinF_Nm_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eDTC_OL_TrqMinF_Nm_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eDTC_OL_TrqMinF_Nm_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eDTC_OL_TrqMinF_Nm_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eDTC_OL_TrqMinF_Nm_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eDTC_OL_TrqMinR_Nm_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eDTC_OL_TrqMinR_Nm_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eDTC_OL_TrqMinR_Nm_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eDTC_OL_TrqMinR_Nm_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eDTC_OL_TrqMinR_Nm_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_OL_TrqMaxF_Nm_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_OL_TrqMaxF_Nm_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_OL_TrqMaxF_Nm_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_OL_TrqMaxF_Nm_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_OL_TrqMaxF_Nm_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_OL_TrqMaxR_Nm_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_OL_TrqMaxR_Nm_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_OL_TrqMaxR_Nm_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_OL_TrqMaxR_Nm_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_OL_TrqMaxR_Nm_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolQual_FL_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolQual_FL_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolQual_FL_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolQual_FL_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolQual_FL_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolQual_FR_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolQual_FR_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolQual_FR_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolQual_FR_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolQual_FR_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolQual_RL_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolQual_RL_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolQual_RL_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolQual_RL_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolQual_RL_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolQual_RR_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolQual_RR_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolQual_RR_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolQual_RR_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolQual_RR_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolRatio_FL_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolRatio_FL_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolRatio_FL_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolRatio_FL_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolRatio_FL_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolRatio_FR_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolRatio_FR_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolRatio_FR_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolRatio_FR_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolRatio_FR_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolRatio_RL_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolRatio_RL_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolRatio_RL_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolRatio_RL_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolRatio_RL_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolRatio_RR_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolRatio_RR_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolRatio_RR_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolRatio_RR_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_TireTolRatio_RR_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_VxEst_kmph_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_VxEst_kmph_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_VxEst_kmph_Fail1Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_VxEst_kmph_Fail2Value;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagOver_eTCS_VxEst_kmph_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA float32 eHLC_eLSD_RELSD_TgtTrq_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_Adherence_TrqMaxF_Nm_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_Adherence_TrqMaxR_Nm_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_Adherence_TrqMinF_Nm_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_Adherence_TrqMinR_Nm_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_Efficiency_TrqMaxF_Nm_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_Efficiency_TrqMaxR_Nm_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_Efficiency_TrqMinF_Nm_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_Efficiency_TrqMinR_Nm_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_OL_Strategic_TrqMaxF_Nm_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_OL_Strategic_TrqMaxR_Nm_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_OL_Strategic_TrqMinF_Nm_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_OL_Strategic_TrqMinR_Nm_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_OL_TactFast_TrqMaxF_Nm_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_OL_TactFast_TrqMaxR_Nm_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_OL_TactFast_TrqMinF_Nm_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_OL_TactFast_TrqMinR_Nm_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_OL_TactSlow_TrqMaxF_Nm_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_OL_TactSlow_TrqMaxR_Nm_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_OL_TactSlow_TrqMinF_Nm_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_OL_TactSlow_TrqMinR_Nm_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_OL_TrqMaxF_Nm_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_OL_TrqMaxR_Nm_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_TireTolQual_FL_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_TireTolQual_FR_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_TireTolQual_RL_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_TireTolQual_RR_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_TireTolRatio_FL_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_TireTolRatio_FR_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_TireTolRatio_RL_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_TireTolRatio_RR_MapVal;
extern MERGEABLE_CAL_PRAGMA float32 eTCS_VxEst_kmph_MapVal;

extern MERGEABLE_CAL_PRAGMA boolean ACC_Wheel_Torque_phyconv_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean NvMout_BEV_TireTol_Ratio_FL_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean NvMout_BEV_TireTol_Ratio_FR_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean NvMout_BEV_TireTol_Ratio_RL_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean NvMout_BEV_TireTol_Ratio_RR_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean NvMout_BEV_TireTol_Stiffness_FL_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean NvMout_BEV_TireTol_Stiffness_FR_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean NvMout_BEV_TireTol_Stiffness_RL_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean NvMout_BEV_TireTol_Stiffness_RR_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean NvMout_BEV_TireTol_p11_FL_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean NvMout_BEV_TireTol_p11_FR_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean NvMout_BEV_TireTol_p11_RL_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean NvMout_BEV_TireTol_p11_RR_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eAWD_IntvActv_b_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eAWD_IntvActv_b_MapVal;
extern MERGEABLE_CAL_PRAGMA boolean eAWD_SplitFactor_Minus_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eAWD_SplitFactor_Plus_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eDTC_OL_TrqMinF_Nm_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eDTC_OL_TrqMinR_Nm_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagOver_OverrideEpromOut_EN;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagOver_OverrideSafetyOut_EN;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagOver_OverrideTrqChainOut_EN;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagOver_OverrideeLSDOut_EN;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagOver_eTCS_6SOAllowed_b_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagOver_eTCS_6SOAllowed_b_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagOver_eTCS_6SOAllowed_b_Fail1Value;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagOver_eTCS_6SOAllowed_b_Fail2Value;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagOver_eTCS_6SOAllowed_b_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA uint8 eHLC_DiagOver_eTCS_AWDDisconnectAllowed_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA uint8 eHLC_DiagOver_eTCS_AWDDisconnectAllowed_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA uint8 eHLC_DiagOver_eTCS_AWDDisconnectAllowed_Fail1Value;
extern MERGEABLE_CAL_PRAGMA uint8 eHLC_DiagOver_eTCS_AWDDisconnectAllowed_Fail2Value;
extern MERGEABLE_CAL_PRAGMA uint8 eHLC_DiagOver_eTCS_AWDDisconnectAllowed_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagOver_eTCS_eDTC_FrontAJOffReq_b_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagOver_eTCS_eDTC_FrontAJOffReq_b_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagOver_eTCS_eDTC_FrontAJOffReq_b_Fail1Value;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagOver_eTCS_eDTC_FrontAJOffReq_b_Fail2Value;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagOver_eTCS_eDTC_FrontAJOffReq_b_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagOver_eTCS_eDTC_RearAJOffReq_b_DiagOffValue;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagOver_eTCS_eDTC_RearAJOffReq_b_ExtFailValue;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagOver_eTCS_eDTC_RearAJOffReq_b_Fail1Value;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagOver_eTCS_eDTC_RearAJOffReq_b_Fail2Value;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagOver_eTCS_eDTC_RearAJOffReq_b_RollsModeValue;
extern MERGEABLE_CAL_PRAGMA uint8 eHLC_DiagQM_RecoverySts_DiagOff;
extern MERGEABLE_CAL_PRAGMA uint8 eHLC_DiagQM_RecoverySts_ExtFail;
extern MERGEABLE_CAL_PRAGMA uint8 eHLC_DiagQM_RecoverySts_Fail1;
extern MERGEABLE_CAL_PRAGMA uint8 eHLC_DiagQM_RecoverySts_Fail2;
extern MERGEABLE_CAL_PRAGMA uint8 eHLC_DiagQM_RecoverySts_On;
extern MERGEABLE_CAL_PRAGMA uint8 eHLC_DiagQM_RecoverySts_RollsMode;
extern MERGEABLE_CAL_PRAGMA uint8 eHLC_TCS_SP_Gear_ReverseEngaged;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_WED_QM_RecoveryStatus_MapEn;
extern MERGEABLE_CAL_PRAGMA uint8 eHLC_WED_QM_RecoveryStatus_MapVal;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_eAWD_QM_RecoveryStatus_MapEn;
extern MERGEABLE_CAL_PRAGMA uint8 eHLC_eAWD_QM_RecoveryStatus_MapVal;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_eLSD_QM_RecoveryStatus_MapEn;
extern MERGEABLE_CAL_PRAGMA uint8 eHLC_eLSD_QM_RecoveryStatus_MapVal;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_eLSD_RELSD_TgtTrq_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_6SOAllowed_b_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_6SOAllowed_b_MapVal;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_AWDDisconnectAllowed_MapEn;
extern MERGEABLE_CAL_PRAGMA uint8 eTCS_AWDDisconnectAllowed_MapVal;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_Adherence_TrqMaxF_Nm_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_Adherence_TrqMaxR_Nm_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_Adherence_TrqMinF_Nm_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_Adherence_TrqMinR_Nm_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_Efficiency_TrqMaxF_Nm_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_Efficiency_TrqMaxR_Nm_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_Efficiency_TrqMinF_Nm_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_Efficiency_TrqMinR_Nm_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_OL_Strategic_TrqMaxF_Nm_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_OL_Strategic_TrqMaxR_Nm_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_OL_Strategic_TrqMinF_Nm_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_OL_Strategic_TrqMinR_Nm_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_OL_TactFast_TrqMaxF_Nm_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_OL_TactFast_TrqMaxR_Nm_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_OL_TactFast_TrqMinF_Nm_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_OL_TactFast_TrqMinR_Nm_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_OL_TactSlow_TrqMaxF_Nm_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_OL_TactSlow_TrqMaxR_Nm_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_OL_TactSlow_TrqMinF_Nm_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_OL_TactSlow_TrqMinR_Nm_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_OL_TrqMaxF_Nm_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_OL_TrqMaxR_Nm_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_TireTolQual_FL_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_TireTolQual_FR_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_TireTolQual_RL_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_TireTolQual_RR_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_TireTolRatio_FL_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_TireTolRatio_FR_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_TireTolRatio_RL_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_TireTolRatio_RR_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_VxEst_kmph_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_eDTC_FrontAJOffReq_b_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_eDTC_FrontAJOffReq_b_MapVal;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_eDTC_RearAJOffReq_b_MapEn;
extern MERGEABLE_CAL_PRAGMA boolean eTCS_eDTC_RearAJOffReq_b_MapVal;

extern INTERMEDIATE float32 NvMout_BEV_TireTol_Ratio_FL_eAppOut;
extern INTERMEDIATE float32 NvMout_BEV_TireTol_Ratio_FR_eAppOut;
extern INTERMEDIATE float32 NvMout_BEV_TireTol_Ratio_RL_eAppOut;
extern INTERMEDIATE float32 NvMout_BEV_TireTol_Ratio_RR_eAppOut;

extern INTERMEDIATE uint8 TcsGearEngaged_eAppOut;

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/

extern void ApplBev_Output(void);

#endif /* APPLBEV_OUTPUT_H */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
