/******************************************************************************\
 *** 
 *** Simulink model       : applbev_EVCU2
 *** TargetLink subsystem : applbev_EVCU2/ApplicationLayerBEV_ac
 *** Codefile             : ApplBEV_Library.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2024-02-19 13:00:04
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : AUTOSAR
 *** AUTOSAR version                          : 4.0.3
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : disabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : enabled
 *** Exploit ranges if not erasable           : enabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : unlimited
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : disabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : disabled
 *** Inlining Threshold                       : 10
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : disabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : D:\users\valsania\Desktop\Proget
 ***                                            ti\EVCU2_Work\SWC\0AF_2402\EVCU2
 ***                                            _SWC_APPLBEV\MDL\applbev_s_prj\a
 ***                                            pplbev_c_prj\config\cconfig_AR.x
 ***                                            ml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLi
 ***                                            nk 4.3\Matlab\Tl\XML\CodeGen\Sty
 ***                                            lesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 4.3p5 from 18-Sep-2019
 *** Code generator version  : Build Id 4.3.0.29 from 2019-09-19 11:35:24
 *** Copyright (c) 2012 dSPACE GmbH\****************************************************************
 **************/

#ifndef APPLBEV_LIBRARY_H
#define APPLBEV_LIBRARY_H

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "Rte_Type.h"

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/

extern float32 ApplBEV_Counter(float32 SApB_Count1_Init, float32 SApB_Count1_Enable, float32
   SApB_Count1_SampleTime, float32 SApB_Count1_Counter_old);
extern float32 ApplBEV_Derivative(float32 SApB_Dervt1_In, float32 SApB_Dervt1_In_old, float32
   SApB_Dervt1_SampleTime);
extern float32 ApplBEV_DiscreteIntegrator(float32 SApB_DscInt1_In, float32 SApB_DscInt1_In_old,
   float32 SApB_DscInt1_AntiWindupMin, float32 SApB_DscInt1_AntiWindupMax, float32
   SApB_DscInt1_Reset, float32 SApB_DscInt1_Hold, float32 SApB_DscInt1_Init, float32
   SApB_DscInt1_SampleTime, float32 SApB_DscInt1_Out_old);
extern float32 ApplBEV_FirstOrderLPF_Init(float32 SApB_LPF1IN1_In, float32 SApB_LPF1IN1_Init,
   float32 SApB_LPF1IN1_Reset, float32 SApB_LPF1IN1_Cutoff, float32 SApB_LPF1IN1_Out_old);
extern float32 ApplBEV_FirstOrderLowPassFilter(float32 SApB_LPF11_In, float32 SApB_LPF11_Cutoff,
   float32 SApB_LPF11_Out_old);
extern float32 ApplBEV_RateLimiter(float32 SApB_RatL1_In, float32 SApB_RatL1_Rate_Up, float32
   SApB_RatL1_Rate_Down, boolean SApB_RatL1_DIsable_Up, boolean SApB_RatL1_Disable_Down, float32
   SApB_RatL1_Init, boolean SApB_RatL1_InitDelaySwitchEn, float32 SApB_RatL1_Out_old);
extern float32 ApplBEV_RateLimiterSaturated(float32 SApB_RatLS1_In, float32 SApB_RatLS1_Rate_Up,
   float32 SApB_RatLS1_Rate_Down, boolean SApB_RatLS1_DIsable_Up, boolean SApB_RatLS1_Disable_Down,
   float32 SApB_RatLS1_Min_Value, float32 SApB_RatLS1_Max_Value, float32 SApB_RatLS1_Init, boolean
   SApB_RatLS1_InitDelaySwitchEn, float32 SApB_RatLS1_Out_old);
extern float32 ApplBEV_RateLimiterSaturationHold(float32 SApB_RatLSH1_In, float32
   SApB_RatLSH1_Rate_Up, float32 SApB_RatLSH1_Rate_Down, boolean SApB_RatLSH1_DIsable_Up, boolean
   SApB_RatLSH1_Disable_Down, boolean SApB_RatLSH1_Hold, float32 SApB_RatLSH1_Min_Value, float32
   SApB_RatLSH1_Max_Value, float32 SApB_RatLSH1_Init, boolean SApB_RatLSH1_InitDelaySwitchEn,
   float32 SApB_RatLSH1_Out_old);
extern float32 ApplBEV_Sign(float32 SApB_Sign1_In);

extern boolean ApplBEV_DebouncerSteps(boolean SApB_DbcnS1_In, boolean SApB_DbcnS1_In_old);
extern boolean ApplBEV_HitCrossingFalling(float32 SApB_HCFall1_In, float32 SApB_HCFall1_In_old,
   float32 SApB_HCFall1_Threshold, boolean SApB_HCFall1_Out_old);
extern boolean ApplBEV_HitCrossingRising(float32 SApB_HCRise1_In, float32 SApB_HCRise1_In_old,
   float32 SApB_HCRise1_Threshold, boolean SApB_HCRise1_Out_old);
extern boolean ApplBEV_Hold(float32 SApB_Hold1_Hold, float32 SApB_Hold1_Reset, boolean
   SApB_Hold1_Out_old);
extern boolean ApplBEV_Relay(boolean SApB_Relay1_Set, boolean SApB_Relay1_Reset, boolean
   SApB_Relay1_Out_old);
extern boolean ApplBEV_SignalsJointManagement(boolean SApB_SgnJnM1_BTestCheck, float32
   SApB_SgnJnM1_Delta_Allowed, float32 SApB_SgnJnM1_In2, float32 SApB_SgnJnM1_In4, float32
   SApB_SgnJnM1_Target, float32 SApB_SgnJnM1_Current);

#endif /* APPLBEV_LIBRARY_H */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
