/******************************************************************************\
 *** 
 *** Simulink model       : applbev_EVCU2
 *** TargetLink subsystem : applbev_EVCU2/ApplicationLayerBEV_ac
 *** Codefile             : ApplBEV.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2024-02-19 12:59:58
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : AUTOSAR
 *** AUTOSAR version                          : 4.0.3
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : disabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : enabled
 *** Exploit ranges if not erasable           : enabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : unlimited
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : disabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : disabled
 *** Inlining Threshold                       : 10
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : disabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : D:\users\valsania\Desktop\Proget
 ***                                            ti\EVCU2_Work\SWC\0AF_2402\EVCU2
 ***                                            _SWC_APPLBEV\MDL\applbev_s_prj\a
 ***                                            pplbev_c_prj\config\cconfig_AR.x
 ***                                            ml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLi
 ***                                            nk 4.3\Matlab\Tl\XML\CodeGen\Sty
 ***                                            lesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 4.3p5 from 18-Sep-2019
 *** Code generator version  : Build Id 4.3.0.29 from 2019-09-19 11:35:24
 *** Copyright (c) 2012 dSPACE GmbH\****************************************************************
 **************/

#ifndef APPLBEV_H
#define APPLBEV_H

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "Rte_Type.h"
#include "tl_defines_a.h"
#include "ApplBEV_Types.h"
#include "ApplBEV_Library.h"

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/

#define APPLBEV_idxTskDiagOff_E ((uint8) 7)

#ifndef MSSBEV_TargetSts_DiagOff
#define MSSBEV_TargetSts_DiagOff ((uint8) 6)
#endif

/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/

extern MERGEABLE_CAL_PRAGMA float32 eHLC_DiagQM_DiagOffInternal_DebTime;

extern MERGEABLE_CAL_PRAGMA t_frontMotor eHLC_ConfigProg; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
extern MERGEABLE_CAL_PRAGMA uint8 eHLC_DiagQM_DiagOffInternal_CmdIgnLk;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagQM_DiagOffInternal_EN;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagQM_DiagOff_EN;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagQM_TargetSts_DiagOff_AWD_EN;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagQM_TargetSts_DiagOff_DTC_EN;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagQM_TargetSts_DiagOff_LNC_EN;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagQM_TargetSts_DiagOff_POff_EN;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagQM_TargetSts_DiagOff_Regen_EN;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagQM_TargetSts_DiagOff_TCS_EN;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagQM_TargetSts_DiagOff_TV_EN;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagQM_TargetSts_DiagOff_WED_EN;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagQM_TargetSts_DiagOff_bTCS_EN;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagQM_TargetSts_DiagOff_bTV_EN;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagQM_TargetSts_DiagOff_eLOCK_EN;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_DiagQM_TargetSts_DiagOff_eLSD_EN;
extern MERGEABLE_CAL_PRAGMA boolean eHLC_GearRemappingEn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */

extern MERGEABLE_CONST uint32 SW_VER_TIME_LLDR_FUNC; /* LSB: 2^0 OFF: 0 MIN/MAX: 1708345921 .. 17083
  45921 */

extern MERGEABLE_CONST uint8 SW_VER_MAJOR_LLDR_FUNC; /* LSB: 2^0 OFF: 0 MIN/MAX: 1 .. 1 */
extern MERGEABLE_CONST uint8 SW_VER_MINOR_LLDR_FUNC; /* LSB: 2^0 OFF: 0 MIN/MAX: 8 .. 8 */
extern MERGEABLE_CONST uint8 SW_VER_PATCH_LLDR_FUNC; /* LSB: 2^0 OFF: 0 MIN/MAX: 1 .. 1 */

extern INTERMEDIATE tBasic_TrqWheelACC_Nm ACCReq_WheelTrq_Nm_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: -36
  878 .. 94190 */
extern INTERMEDIATE float32 BrakeDiscTempFront_degC_eAppIn;
extern INTERMEDIATE float32 BrakeDiscTempRear_degC_eAppIn;
extern INTERMEDIATE float32 BrakeTrqDrv_Nm_eAppIn;
extern INTERMEDIATE float32 BrakeTrq_Nm_eAppIn;
extern INTERMEDIATE float32 DriverRequestedTorque_Filt_eAppIn;
extern INTERMEDIATE float32 DriverRequestedTorque_noFilt_eAppIn;
extern INTERMEDIATE float32 InvrCmdMgm_TrqTgtF_Nm_eAppIn;
extern INTERMEDIATE float32 InvrCmdMgm_TrqTgtR_Nm_eAppIn;
extern INTERMEDIATE float32 NvMin_TireTol_Ratio_FL_eAppIn;
extern INTERMEDIATE float32 NvMin_TireTol_Ratio_FR_eAppIn;
extern INTERMEDIATE float32 NvMin_TireTol_Ratio_RL_eAppIn;
extern INTERMEDIATE float32 NvMin_TireTol_Ratio_RR_eAppIn;
extern INTERMEDIATE float32 NvMin_TireTol_Stiffness_FL_eAppIn;
extern INTERMEDIATE float32 NvMin_TireTol_Stiffness_FR_eAppIn;
extern INTERMEDIATE float32 NvMin_TireTol_Stiffness_RL_eAppIn;
extern INTERMEDIATE float32 NvMin_TireTol_Stiffness_RR_eAppIn;
extern INTERMEDIATE float32 NvMin_TireTol_p11_FL_eAppIn;
extern INTERMEDIATE float32 NvMin_TireTol_p11_FR_eAppIn;
extern INTERMEDIATE float32 NvMin_TireTol_p11_RL_eAppIn;
extern INTERMEDIATE float32 NvMin_TireTol_p11_RR_eAppIn;
extern INTERMEDIATE float32 R_Diff_TRQ_RQ_eAppIn;
extern INTERMEDIATE float32 Rear_Diff_BSM_RQ_eAppIn;
extern INTERMEDIATE float32 RegenCapacityFront_eAppIn;
extern INTERMEDIATE float32 RegenCapacityRear_eAppIn;
extern INTERMEDIATE float32 RegenRIP_Efficiency_eAppIn;
extern INTERMEDIATE float32 RideHeight_FL_mm_eAppIn;
extern INTERMEDIATE float32 RideHeight_FR_mm_eAppIn;
extern INTERMEDIATE float32 RideHeight_RL_mm_eAppIn;
extern INTERMEDIATE float32 RideHeight_RR_mm_eAppIn;
extern INTERMEDIATE float32 ToMinF_eAppIn;
extern INTERMEDIATE float32 ToMinR_eAppIn;
extern INTERMEDIATE float32 To_Strategic_eAppIn;
extern INTERMEDIATE float32 To_Tact_Engine_Fast_eAppIn;
extern INTERMEDIATE float32 To_Tact_Engine_Slow_eAppIn;
extern INTERMEDIATE float32 TransTrqRatio_eAppIn;
extern INTERMEDIATE float32 TrqLimPTOP_HnAWD_F_Nm_eAppIn;
extern INTERMEDIATE float32 TrqLimPTOP_HnAWD_R_Nm_eAppIn;
extern INTERMEDIATE float32 TrqLimPTOP_HpAWD_F_Nm_eAppIn;
extern INTERMEDIATE float32 TrqLimPTOP_HpAWD_R_Nm_eAppIn;
extern INTERMEDIATE float32 TrqLimPTOP_TrqMaxF_Nm_eAppIn;
extern INTERMEDIATE float32 TrqLimPTOP_TrqMaxR_Nm_eAppIn;
extern INTERMEDIATE float32 TrqLimPTOP_TrqMinF_Nm_eAppIn;
extern INTERMEDIATE float32 TrqLimPTOP_TrqMinR_Nm_eAppIn;
extern INTERMEDIATE float32 TrqLimPTOS_An_F_Nm_eAppIn;
extern INTERMEDIATE float32 TrqLimPTOS_Ap_F_Nm_eAppIn;
extern INTERMEDIATE float32 TrqLimPTOS_Bn_R_Nm_eAppIn;
extern INTERMEDIATE float32 TrqLimPTOS_Bp_R_Nm_eAppIn;
extern INTERMEDIATE float32 TrqLimPTOS_En_F_Nm_eAppIn;
extern INTERMEDIATE float32 TrqLimPTOS_En_R_Nm_eAppIn;
extern INTERMEDIATE float32 TrqLimPTOS_Ep_F_Nm_eAppIn;
extern INTERMEDIATE float32 TrqLimPTOS_Ep_R_Nm_eAppIn;
extern INTERMEDIATE float32 TrqSpltFREff_TrqTgtF_Nm_eAppIn;
extern INTERMEDIATE float32 TrqSpltFREff_TrqTgtR_Nm_eAppIn;
extern INTERMEDIATE float32 TrqSpltMot_TrqTgtF_Nm_eAppIn;
extern INTERMEDIATE float32 TrqSpltMot_TrqTgtF_NoRgnBrk_Nm_eAppIn;
extern INTERMEDIATE float32 TrqSpltMot_TrqTgtR_Nm_eAppIn;
extern INTERMEDIATE float32 TrqSpltMot_TrqTgtR_NoRgnBrk_Nm_eAppIn;
extern INTERMEDIATE float32 eAWD_SplitFactor_Minus_eAppOut;
extern INTERMEDIATE float32 eAWD_SplitFactor_Plus_eAppOut;
extern INTERMEDIATE float32 eDTC_OL_TrqMinF_Nm_eAppOut;
extern INTERMEDIATE float32 eDTC_OL_TrqMinR_Nm_eAppOut;
extern INTERMEDIATE float32 eHLC_eLSD_RELSD_TgtTrq_eAppOut;
extern INTERMEDIATE float32 eTCS_Adherence_TrqMaxF_Nm_eAppOut;
extern INTERMEDIATE float32 eTCS_Adherence_TrqMaxR_Nm_eAppOut;
extern INTERMEDIATE float32 eTCS_Adherence_TrqMinF_Nm_eAppOut;
extern INTERMEDIATE float32 eTCS_Adherence_TrqMinR_Nm_eAppOut;
extern INTERMEDIATE float32 eTCS_Efficiency_TrqMaxF_Nm_eAppOut;
extern INTERMEDIATE float32 eTCS_Efficiency_TrqMaxR_Nm_eAppOut;
extern INTERMEDIATE float32 eTCS_Efficiency_TrqMinF_Nm_eAppOut;
extern INTERMEDIATE float32 eTCS_Efficiency_TrqMinR_Nm_eAppOut;
extern INTERMEDIATE float32 eTCS_OL_Strategic_TrqMaxF_Nm_eAppOut;
extern INTERMEDIATE float32 eTCS_OL_Strategic_TrqMaxR_Nm_eAppOut;
extern INTERMEDIATE float32 eTCS_OL_Strategic_TrqMinF_Nm_eAppOut;
extern INTERMEDIATE float32 eTCS_OL_Strategic_TrqMinR_Nm_eAppOut;
extern INTERMEDIATE float32 eTCS_OL_TactFast_TrqMaxF_Nm_eAppOut;
extern INTERMEDIATE float32 eTCS_OL_TactFast_TrqMaxR_Nm_eAppOut;
extern INTERMEDIATE float32 eTCS_OL_TactFast_TrqMinF_Nm_eAppOut;
extern INTERMEDIATE float32 eTCS_OL_TactFast_TrqMinR_Nm_eAppOut;
extern INTERMEDIATE float32 eTCS_OL_TactSlow_TrqMaxF_Nm_eAppOut;
extern INTERMEDIATE float32 eTCS_OL_TactSlow_TrqMaxR_Nm_eAppOut;
extern INTERMEDIATE float32 eTCS_OL_TactSlow_TrqMinF_Nm_eAppOut;
extern INTERMEDIATE float32 eTCS_OL_TactSlow_TrqMinR_Nm_eAppOut;
extern INTERMEDIATE float32 eTCS_OL_TrqMaxF_Nm_eAppOut;
extern INTERMEDIATE float32 eTCS_OL_TrqMaxR_Nm_eAppOut;
extern INTERMEDIATE float32 eTCS_TireTolQual_FL_eAppOut;
extern INTERMEDIATE float32 eTCS_TireTolQual_FR_eAppOut;
extern INTERMEDIATE float32 eTCS_TireTolQual_RL_eAppOut;
extern INTERMEDIATE float32 eTCS_TireTolQual_RR_eAppOut;
extern INTERMEDIATE float32 eTCS_TireTolRatio_FL_eAppOut;
extern INTERMEDIATE float32 eTCS_TireTolRatio_FR_eAppOut;
extern INTERMEDIATE float32 eTCS_TireTolRatio_RL_eAppOut;
extern INTERMEDIATE float32 eTCS_TireTolRatio_RR_eAppOut;
extern INTERMEDIATE float32 eTCS_VxEst_kmph_eAppOut;

extern INTERMEDIATE tBasic_Acc_mps2 AxCom_mps2_eAppIn; /* LSB: 0.01 OFF: 0 MIN/MAX: -50 .. 50 */
extern INTERMEDIATE tBasic_Acc_mps2 AyCom_mps2_eAppIn; /* LSB: 0.01 OFF: 0 MIN/MAX: -50 .. 50 */
extern INTERMEDIATE tBasic_TrqReqBSM_Nm BSM_TorqueRequest_Nm_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: -50
  0 .. 1546 */
extern INTERMEDIATE tBasic_Percent0to100 BrakeTravelSts_prc_eAppIn; /* LSB: 0.01 OFF: 0 MIN/MAX: 0 .
  . 100 */
extern INTERMEDIATE tBasic_Angle_deg DvolCom_deg_eAppIn; /* LSB: 0.1 OFF: 0 MIN/MAX: -720 .. 720 */
extern INTERMEDIATE tBasic_AngleGrad_degps DvolGradCom_degps_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: -2000 .. 2094
   Description: Angle Gradient */
extern INTERMEDIATE tBasic_ELSDRrLkTrq_Nm ELSDRrLkTrq_Nm_AppIn; /* LSB: 10 OFF: 0 MIN/MAX: 0 .. 5100
    */
extern INTERMEDIATE tBasic_Temp_deg EnvirTempCom_deg_eAppIn; /* LSB: 0.1 OFF: 0 MIN/MAX: -90 .. 180
   */
extern INTERMEDIATE tBasic_CurrentHVBat_A HVBat_Current_A_eAppIn; /* LSB: 0.1 OFF: 0 MIN/MAX: -1638.
   4 .. 1638.2 */
extern INTERMEDIATE sint16 MCPA_Speed_rpm_eAppIn;
extern INTERMEDIATE tBasic_MCPxTrqAch_Nm MCPA_TrqAchAEMD_Nm_eAppIn; /* LSB: 2^-3 OFF: 0 MIN/MAX: -51
   2 .. 511.875 */
extern INTERMEDIATE tBasic_MCPxTrqAch_Nm MCPA_TrqAch_Nm_eAppIn; /* LSB: 2^-3 OFF: 0 MIN/MAX: -512 ..
    511.875 */
extern INTERMEDIATE tBasic_MCPxTrqAch_Nm MCPA_TrqMax_Nm_eAppIn; /* LSB: 2^-3 OFF: 0 MIN/MAX: -512 ..
    511.875 */
extern INTERMEDIATE tBasic_MCPxTrqAch_Nm MCPA_TrqMin_Nm_eAppIn; /* LSB: 2^-3 OFF: 0 MIN/MAX: -512 ..
    511.875 */
extern INTERMEDIATE sint16 MCPB_Speed_rpm_eAppIn;
extern INTERMEDIATE tBasic_MCPxTrqAch_Nm MCPB_TrqAchAEMD_Nm_eAppIn; /* LSB: 2^-3 OFF: 0 MIN/MAX: -51
   2 .. 511.875 */
extern INTERMEDIATE tBasic_MCPxTrqAch_Nm MCPB_TrqAch_Nm_eAppIn; /* LSB: 2^-3 OFF: 0 MIN/MAX: -512 ..
    511.875 */
extern INTERMEDIATE tBasic_MCPxTrqAch_Nm MCPB_TrqMax_Nm_eAppIn; /* LSB: 2^-3 OFF: 0 MIN/MAX: -512 ..
    511.875 */
extern INTERMEDIATE tBasic_MCPxTrqAch_Nm MCPB_TrqMin_Nm_eAppIn; /* LSB: 2^-3 OFF: 0 MIN/MAX: -512 ..
    511.875 */
extern INTERMEDIATE tBasic_BrakePressure_bar MCylPresCom_bar_eAppIn; /* LSB: 0.1 OFF: 0 MIN/MAX: 0 .
   . 200 */
extern INTERMEDIATE tBasic_AngleSpeed_degps PsipCom_degps_eAppIn; /* LSB: 0.01 OFF: 0 MIN/MAX: -300 
   .. 300 */
extern INTERMEDIATE tBasic_TrqBrakeOffsetRegen_Nm RegBrakeOffstReqFront_Nm_eAppIn; /* LSB: 2^0 OFF: 
   0 MIN/MAX: 0 .. 4095 */
extern INTERMEDIATE tBasic_TrqBrakeOffsetRegen_Nm RegBrakeOffstReqRear_Nm_eAppIn; /* LSB: 2^0 OFF: 0
    MIN/MAX: 0 .. 4095 */
extern INTERMEDIATE tBasic_Slope_prc RoadSlopeCom_prc_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: -200 .. 20
   0 */
extern INTERMEDIATE tBasic_Vx_Veh_kmph VxCom_Estim_kmph_eAppIn; /* LSB: 2^-4 OFF: 0 MIN/MAX: -512 ..
    512 */
extern INTERMEDIATE tBasic_WheelSpeed_kmph WheelSpeed_FL_Com_kmph_eAppIn; /* LSB: 2^-4 OFF: 0 MIN/MA
   X: -512 .. 512 */
extern INTERMEDIATE tBasic_WheelSpeed_kmph WheelSpeed_FR_Com_kmph_eAppIn; /* LSB: 2^-4 OFF: 0 MIN/MA
   X: -512 .. 512 */
extern INTERMEDIATE tBasic_WheelSpeed_kmph WheelSpeed_RL_Com_kmph_eAppIn; /* LSB: 2^-4 OFF: 0 MIN/MA
   X: -512 .. 512 */
extern INTERMEDIATE tBasic_WheelSpeed_kmph WheelSpeed_RR_Com_kmph_eAppIn; /* LSB: 2^-4 OFF: 0 MIN/MA
   X: -512 .. 512 */

extern INTERMEDIATE tBasic_RecSt ABSFailSts_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128 */
extern INTERMEDIATE boolean ABSFailSts_eAppIn;
extern INTERMEDIATE tBasic_RecSt ABSHighSlipFlg_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE boolean ABSHighSlipFlg_eAppIn;
extern INTERMEDIATE boolean ABSStsFL_eAppIn;
extern INTERMEDIATE boolean ABSStsFR_eAppIn;
extern INTERMEDIATE boolean ABSStsRL_eAppIn;
extern INTERMEDIATE boolean ABSStsRR_eAppIn;
extern INTERMEDIATE tBasic_RecSt ABSSts_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE boolean ABSSts_eAppIn;
extern INTERMEDIATE tBasic_RecSt ACCReq_WheelTrqEn_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE boolean ACCReq_WheelTrqEn_eAppIn;
extern INTERMEDIATE tBasic_RecSt ACCReq_WheelTrq_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE uint8 AWDDisconnectFeedback_eAppIn;
extern INTERMEDIATE tBasic_RecSt AxComFailSts_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128 */
extern INTERMEDIATE boolean AxComFailSts_eAppIn;
extern INTERMEDIATE tBasic_RecSt AxCom_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE uint8 AxleLckrSEL_SW_eAppIn;
extern INTERMEDIATE tBasic_RecSt AyComFailSts_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128 */
extern INTERMEDIATE boolean AyComFailSts_eAppIn;
extern INTERMEDIATE tBasic_RecSt AyCom_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE tBasic_RecSt BSM_TorqueReduct_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE boolean BSM_TorqueReduct_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1 */
extern INTERMEDIATE tBasic_RecSt BSM_TorqueRequest_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE uint8 BrakeBTCS_BTV_FrontSts_eAppIn;
extern INTERMEDIATE uint8 BrakeBTCS_BTV_RearSts_eAppIn;
extern INTERMEDIATE boolean BrakeOverTemp_eAppIn;
extern INTERMEDIATE tBasic_RecSt BrakePdlSwtSts_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE boolean BrakePdlSwtSts_eAppIn;
extern INTERMEDIATE tBasic_RecSt BrakeTravelSts_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE tBasic_RecSt BrakeTrqDrv_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE tBasic_RecSt BrakeTrq_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE tBasic_RecSt CmdIgnSts_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128 */
extern INTERMEDIATE uint8 CmdIgnSts_eAppIn;
extern INTERMEDIATE tBasic_RecSt CruiseControlSts_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
    */
extern INTERMEDIATE tBasic_RecSt DriverSlipControlSel_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 ..
    128 */
extern INTERMEDIATE uint8 DriverSlipControlSel_eAppIn;
extern INTERMEDIATE tBasic_RecSt DvolCom_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE tBasic_RecSt DvolFailSts_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128 */
extern INTERMEDIATE boolean DvolFailSts_eAppIn;
extern INTERMEDIATE tBasic_RecSt DvolGradCom_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE tBasic_RecSt EBDFailSts_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128 */
extern INTERMEDIATE boolean EBDFailSts_eAppIn;
extern INTERMEDIATE tBasic_RecSt EBDSts_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128 */
extern INTERMEDIATE boolean EBDSts_eAppIn;
extern INTERMEDIATE tBasic_RecSt ELSDRrLkTrq_RecSt_AppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE tBasic_ELSDRrSysStat ELSDRrSysStat_AppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 15 */
extern INTERMEDIATE tBasic_RecSt ELSDRrSysStat_RecSt_AppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE tBasic_RecSt ELSDRrTempAvl_RecSt_AppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE tBasic_ELSDRrTempAvl_prc ELSDRrTempAvl_prc_AppIn;
extern INTERMEDIATE tBasic_RecSt ESCFailSts_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128 */
extern INTERMEDIATE boolean ESCFailSts_eAppIn;
extern INTERMEDIATE tBasic_RecSt ESCInterv_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE boolean ESCInterv_eAppIn;
extern INTERMEDIATE tBasic_RecSt ESCStsFL_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE boolean ESCStsFL_eAppIn;
extern INTERMEDIATE tBasic_RecSt ESCStsFR_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE boolean ESCStsFR_eAppIn;
extern INTERMEDIATE tBasic_RecSt ESCStsRL_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE boolean ESCStsRL_eAppIn;
extern INTERMEDIATE tBasic_RecSt ESCStsRR_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE boolean ESCStsRR_eAppIn;
extern INTERMEDIATE tBasic_RecSt ESCSts_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE boolean ESCSts_eAppIn;
extern INTERMEDIATE tBasic_RecSt ESC_OFF_ReqForTCS_OFF_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE boolean ESC_OFF_ReqForTCS_OFF_eAppIn;
extern INTERMEDIATE tBasic_RecSt EnvirTempCom_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE uint8 ExternalBrkRequestsDisabled_eAppIn;
extern INTERMEDIATE boolean FrontAxle_Max_Rq_BSM_eAppIn;
extern INTERMEDIATE boolean FrontAxle_Min_Rq_BSM_eAppIn;
extern INTERMEDIATE boolean FunctionSts_eAppIn;
extern INTERMEDIATE t_VDCM_PWT2_GasPedalPosition_VDCM GasPedalPosition_Internal_eAppIn; /* 
   Unit: %
   LSB: 0.392 OFF: 0 MIN/MAX: 0 .. 99.96 */
extern INTERMEDIATE uint8 GearEngaged_Internal_eAppIn;
extern INTERMEDIATE uint8 GearShiftType_eAppIn;
extern INTERMEDIATE boolean GetSRMR_b_Lv2AccelPdlPosFlt_eAppIn;
extern INTERMEDIATE tBasic_RecSt IPC_TorqueVectoringSel_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 
   .. 128 */
extern INTERMEDIATE uint8 IPC_TorqueVectoringSel_eAppIn;
extern INTERMEDIATE tBasic_RecSt MCPA_InvState_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128 */
extern INTERMEDIATE uint8 MCPA_InvState_eAppIn;
extern INTERMEDIATE tBasic_RecSt MCPA_Speed_rpm_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   */
extern INTERMEDIATE tBasic_RecSt MCPA_TrqAchAEMD_Nm_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1
   28 */
extern INTERMEDIATE tBasic_RecSt MCPA_TrqAch_Nm_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   */
extern INTERMEDIATE tBasic_RecSt MCPA_TrqMax_Nm_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   */
extern INTERMEDIATE tBasic_RecSt MCPA_TrqMin_Nm_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   */
extern INTERMEDIATE tBasic_RecSt MCPB_InvState_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128 */
extern INTERMEDIATE uint8 MCPB_InvState_eAppIn;
extern INTERMEDIATE tBasic_RecSt MCPB_Speed_rpm_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   */
extern INTERMEDIATE tBasic_RecSt MCPB_TrqAchAEMD_Nm_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 1
   28 */
extern INTERMEDIATE tBasic_RecSt MCPB_TrqAch_Nm_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   */
extern INTERMEDIATE tBasic_RecSt MCPB_TrqMax_Nm_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   */
extern INTERMEDIATE tBasic_RecSt MCPB_TrqMin_Nm_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   */
extern INTERMEDIATE tBasic_RecSt MCylPresCom_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE t_MSSBEV_TgtSts MSSBEV_DRV_PoffRegen_TargetSts_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MA
   X: 0 .. 42 */
extern INTERMEDIATE t_MSSBEV_TgtSts MSSBEV_Regen_TargetSts_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 
   42 */
extern INTERMEDIATE t_MSSBEV_TgtSts MSSBEV_WED_TargetSts_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 42
    */
extern INTERMEDIATE t_MSSBEV_TgtSts MSSBEV_bTCS_TargetSts_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 4
   2 */
extern INTERMEDIATE t_MSSBEV_TgtSts MSSBEV_bTV_TargetSts_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 42
    */
extern INTERMEDIATE t_MSSBEV_TgtSts MSSBEV_eAWD_TargetSts_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 4
   2 */
extern INTERMEDIATE t_MSSBEV_TgtSts MSSBEV_eDTC_TargetSts_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 4
   2 */
extern INTERMEDIATE t_MSSBEV_TgtSts MSSBEV_eLNC_TargetSts_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 4
   2 */
extern INTERMEDIATE t_MSSBEV_TgtSts MSSBEV_eTCS_TargetSts_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 4
   2 */
extern INTERMEDIATE t_MSSBEV_TgtSts MSSBEV_eTV_TargetSts_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 42
    */
extern INTERMEDIATE boolean PowertrainPrplsnActv_Internal_eAppIn;
extern INTERMEDIATE boolean ProxiExt_CanNode105_ELSDM_En_eAppIn;
extern INTERMEDIATE tBasic_RecSt PsipComFailSts_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   */
extern INTERMEDIATE boolean PsipComFailSts_eAppIn;
extern INTERMEDIATE tBasic_RecSt PsipCom_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE uint8 RaceModeOptionSts_eAppIn;
extern INTERMEDIATE boolean RearAxle_Max_Rq_BSM_eAppIn;
extern INTERMEDIATE boolean RearAxle_Min_Rq_BSM_eAppIn;
extern INTERMEDIATE tBasic_RecSt RearDiffModeCom_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE tBasic_RecSt RearDiffTrqCom_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE tBasic_RecSt RegBrakeFailSts_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   */
extern INTERMEDIATE boolean RegBrakeFailSts_eAppIn;
extern INTERMEDIATE tBasic_RecSt RegBrakeOffstReqFront_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .
   . 128 */
extern INTERMEDIATE tBasic_RecSt RegBrakeOffstReqRear_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 ..
    128 */
extern INTERMEDIATE tBasic_RecSt RideHeight_FL_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE tBasic_RecSt RideHeight_FR_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE tBasic_RecSt RideHeight_RL_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE tBasic_RecSt RideHeight_RR_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE tBasic_RecSt RoadSlopeCom_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE uint8 RrAxleLckrStat_eAppIn;
extern INTERMEDIATE uint8 TargetGear_Internal_eAppIn;
extern INTERMEDIATE uint8 TerrainModeStat_Internal_eAppIn;
extern INTERMEDIATE tBasic_RecSt TrailerConnectionSts_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE uint8 TrailerConnectionSts_eAppIn;
extern INTERMEDIATE tBasic_RecSt TrailerGenFailSts_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 12
   8 */
extern INTERMEDIATE boolean TrailerGenFailSts_eAppIn;
extern INTERMEDIATE tBasic_RecSt VehEstMovDir_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE tBasic_VehEstMovDir VehEstMovDir_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 3 */
extern INTERMEDIATE tBasic_RecSt VehRollsModeAct_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   */
extern INTERMEDIATE boolean VehRollsModeAct_eAppIn;
extern INTERMEDIATE tBasic_RecSt VxCom_Estim_RecSt_eAppIn; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128 */
extern INTERMEDIATE tBasic_RecSt WheelSpeed_FL_Com_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE tBasic_RecSt WheelSpeed_FR_Com_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE tBasic_RecSt WheelSpeed_RL_Com_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE tBasic_RecSt WheelSpeed_RR_Com_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE tBasic_RecSt WheelSpin_FL_Com_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE uint8 WheelSpin_FL_Com_eAppIn;
extern INTERMEDIATE tBasic_RecSt WheelSpin_FR_Com_RecSt_eAppIn; /* 
   LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 128
   Description: Variable State */
extern INTERMEDIATE uint8 WheelSpin_FR_Com_eAppIn;
extern INTERMEDIATE uint8 WheelSpin_RL_Com_eAppIn;
extern INTERMEDIATE uint8 WheelSpin_RR_Com_eAppIn;
extern INTERMEDIATE boolean eAWD_IntvActv_b_eAppOut;
extern INTERMEDIATE uint8 eHLC_WED_QM_RecoveryStatus_eAppOut;
extern INTERMEDIATE uint8 eHLC_eAWD_QM_RecoveryStatus_eAppOut;
extern INTERMEDIATE uint8 eHLC_eLSD_QM_RecoveryStatus_eAppOut;
extern INTERMEDIATE boolean eTCS_6SOAllowed_b_eAppOut;
extern INTERMEDIATE uint8 eTCS_AWDDisconnectAllowed_eAppOut;

extern MERGEABLE_GLOBAL float32 SApB_Count1_Counter_a;

extern MERGEABLE_GLOBAL boolean SApB_DbcnS1_Out_a;

extern Float Value_la;
extern Float Value_ma;
extern Float Value_na;
extern Float Value_oa;
extern Float Value_pa;
extern Float Value_qa;
extern Float Value_ra;
extern Float Value_sa;

extern TeTIMR_e_RaceModeSts Value_yh; /* LSB: 2^0 OFF: 0 MIN/MAX: 0 .. 255 */

/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/

/* start of memory section 'CODE' */
#define LLDR_FUNC_START_SEC_CODE
#include "LLDR_FUNC_MemMap.h"
FUNC(void, LLDR_FUNC_CODE) ApplicationLayerBEV_run(Boolean ev_PowerOn, Boolean ev_10msec);

/* end of memory section 'CODE' */
#define LLDR_FUNC_STOP_SEC_CODE
#include "LLDR_FUNC_MemMap.h"

#endif /* APPLBEV_H */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
