/******************************************************************************\
 *** 
 *** Simulink model       : applbev_EVCU2
 *** TargetLink subsystem : applbev_EVCU2/ApplicationLayerBEV_ac
 *** Codefile             : ApplBEV_Library.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2024-02-19 13:00:03
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : AUTOSAR
 *** AUTOSAR version                          : 4.0.3
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : disabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : enabled
 *** Exploit ranges if not erasable           : enabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : unlimited
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : disabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : disabled
 *** Inlining Threshold                       : 10
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : disabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : D:\users\valsania\Desktop\Proget
 ***                                            ti\EVCU2_Work\SWC\0AF_2402\EVCU2
 ***                                            _SWC_APPLBEV\MDL\applbev_s_prj\a
 ***                                            pplbev_c_prj\config\cconfig_AR.x
 ***                                            ml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLi
 ***                                            nk 4.3\Matlab\Tl\XML\CodeGen\Sty
 ***                                            lesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 4.3p5 from 18-Sep-2019
 *** Code generator version  : Build Id 4.3.0.29 from 2019-09-19 11:35:24
 *** Copyright (c) 2012 dSPACE GmbH\****************************************************************
 **************/

#ifndef APPLBEV_LIBRARY_C
#define APPLBEV_LIBRARY_C

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include <math.h>
#include "ApplBEV_Library.h"

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

/******************************************************************************\
 ***  FUNCTION:
 ***      ApplBEV_Counter
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      float32            SApB_Count1_Init    
 ***      float32            SApB_Count1_Enable  
 ***      float32            SApB_Count1_SampleTime 
 ***      float32            SApB_Count1_Counter_old 
 ***
 ***  RETURNS:
 ***      float32
 ***
 ***  SETTINGS:
 ***
\******************************************************************************/
float32 ApplBEV_Counter(float32 SApB_Count1_Init, float32 SApB_Count1_Enable, float32
  SApB_Count1_SampleTime, float32 SApB_Count1_Counter_old)
{
   float32 SApB_Count1_Switch2;

   /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV
      _core/ApplicationLayerBEV_Scheduler/DiagQM_Mgm/Debouncer Time/Debouncer St
      eps/Counter/Counter_Sub/Switch2 */
   if (SApB_Count1_Enable >= 0.5F) {
      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/ApplicationLayerBEV_Scheduler/DiagQM_Mgm/Debouncer Time/Deboun
         cer Steps/Counter/Counter_Sub/Switch2
         # combined # Sum: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Applic
         ationLayerBEV_core/ApplicationLayerBEV_Scheduler/DiagQM_Mgm/Debouncer T
         ime/Debouncer Steps/Counter/Counter_Sub/sum */
      SApB_Count1_Switch2 = SApB_Count1_SampleTime + SApB_Count1_Counter_old;
   }
   else {
      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/ApplicationLayerBEV_Scheduler/DiagQM_Mgm/Debouncer Time/Deboun
         cer Steps/Counter/Counter_Sub/Switch2 */
      SApB_Count1_Switch2 = SApB_Count1_Init;
   }

   /* # combined # TargetLink outport: ApplicationLayerBEV_ac/ApplicationLayerBE
      V_run/ApplicationLayerBEV_core/ApplicationLayerBEV_Scheduler/DiagQM_Mgm/De
      bouncer Time/Debouncer Steps/Counter/Counter_Sub/Counter */
   return SApB_Count1_Switch2;
}

/******************************************************************************\
 ***  FUNCTION:
 ***      ApplBEV_Derivative
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      float32            SApB_Dervt1_In      
 ***      float32            SApB_Dervt1_In_old  
 ***      float32            SApB_Dervt1_SampleTime 
 ***
 ***  RETURNS:
 ***      float32
 ***
 ***  SETTINGS:
 ***
\******************************************************************************/
float32 ApplBEV_Derivative(float32 SApB_Dervt1_In, float32 SApB_Dervt1_In_old, float32
  SApB_Dervt1_SampleTime)
{
   float32 SApB_Dervt1_Sum4;
   float32 SApB_Dervt1_product;

   /* Sum: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV_co
      re/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_TCS_MAIN/T
      CS_MAIN/TM02_SIGNALS_PROCESSING/SP03_VehicleSignals/VS04_Wheels_Signals/VS
      02_Wheels_Acceleration/Derivative/Derivative/Derivative_Sub/Sum4 */
   SApB_Dervt1_Sum4 = SApB_Dervt1_In - SApB_Dervt1_In_old;

   /* Product: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBE
      V_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_TCS_MA
      IN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP03_VehicleSignals/VS04_Wheels_Signal
      s/VS02_Wheels_Acceleration/Derivative/Derivative/Derivative_Sub/product */
   if (SApB_Dervt1_SampleTime != 0.F) {
      SApB_Dervt1_product = SApB_Dervt1_Sum4 / SApB_Dervt1_SampleTime;
   }
   else {
      if (SApB_Dervt1_Sum4 < 0.F) {
         SApB_Dervt1_product = -3.402823466e+38F;
      }
      else {
         SApB_Dervt1_product = 3.402823466e+38F;
      }
   }

   /* # combined # TargetLink outport: ApplicationLayerBEV_ac/ApplicationLayerBE
      V_run/ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_
      CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP03_VehicleSi
      gnals/VS04_Wheels_Signals/VS02_Wheels_Acceleration/Derivative/Derivative/D
      erivative_Sub/Out */
   return SApB_Dervt1_product;
}

/******************************************************************************\
 ***  FUNCTION:
 ***      ApplBEV_DiscreteIntegrator
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      float32            SApB_DscInt1_In     
 ***      float32            SApB_DscInt1_In_old 
 ***      float32            SApB_DscInt1_AntiWindupMin 
 ***      float32            SApB_DscInt1_AntiWindupMax 
 ***      float32            SApB_DscInt1_Reset  
 ***      float32            SApB_DscInt1_Hold   
 ***      float32            SApB_DscInt1_Init   
 ***      float32            SApB_DscInt1_SampleTime 
 ***      float32            SApB_DscInt1_Out_old 
 ***
 ***  RETURNS:
 ***      float32
 ***
 ***  SETTINGS:
 ***
\******************************************************************************/
float32 ApplBEV_DiscreteIntegrator(float32 SApB_DscInt1_In, float32 SApB_DscInt1_In_old, float32
  SApB_DscInt1_AntiWindupMin, float32 SApB_DscInt1_AntiWindupMax, float32 SApB_DscInt1_Reset,
  float32 SApB_DscInt1_Hold, float32 SApB_DscInt1_Init, float32 SApB_DscInt1_SampleTime, float32
  SApB_DscInt1_Out_old)
{
   float32 SApB_DscInt1_Sum8;
   float32 SApB_DscInt1_Switch;
   float32 SApB_DscInt1_Switch1;

   /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV
      _core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_TCS_MAI
      N/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/HI13_Side_Slip_Ang
      le_Estimation/Discrete Integrator/Discrete Integrator/Discrete Integrator_
      Sub/Switch */
   if (SApB_DscInt1_Reset >= 0.5F) {
      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_T
         CS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/HI13_Side
         _Slip_Angle_Estimation/Discrete Integrator/Discrete Integrator/Discrete
          Integrator_Sub/Switch */
      SApB_DscInt1_Switch = SApB_DscInt1_Init;
   }
   else {
      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_T
         CS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/HI13_Side
         _Slip_Angle_Estimation/Discrete Integrator/Discrete Integrator/Discrete
          Integrator_Sub/Switch1 */
      if (SApB_DscInt1_Hold >= 0.5F) {
         /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLa
            yerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/T
            CS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/
            HI13_Side_Slip_Angle_Estimation/Discrete Integrator/Discrete Integra
            tor/Discrete Integrator_Sub/Switch1 */
         SApB_DscInt1_Switch1 = 0.F;
      }
      else {
         /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLa
            yerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/T
            CS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/
            HI13_Side_Slip_Angle_Estimation/Discrete Integrator/Discrete Integra
            tor/Discrete Integrator_Sub/Switch1
            # combined # Product: ApplicationLayerBEV_ac/ApplicationLayerBEV_run
            /ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE
            _CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_Ha
            ndlingIndices/HI13_Side_Slip_Angle_Estimation/Discrete Integrator/Di
            screte Integrator/Discrete Integrator_Sub/Product5
            # combined # Gain: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Ap
            plicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CO
            NTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_Handl
            ingIndices/HI13_Side_Slip_Angle_Estimation/Discrete Integrator/Discr
            ete Integrator/Discrete Integrator_Sub/Gain
            # combined # Sum: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/App
            licationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CON
            TROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_Handli
            ngIndices/HI13_Side_Slip_Angle_Estimation/Discrete Integrator/Discre
            te Integrator/Discrete Integrator_Sub/Sum4 */
         SApB_DscInt1_Switch1 = SApB_DscInt1_SampleTime * ((SApB_DscInt1_In + SApB_DscInt1_In_old) *
           0.5F);
      }

      /* Sum: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV
         _core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_TCS_
         MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/HI13_Side_Sl
         ip_Angle_Estimation/Discrete Integrator/Discrete Integrator/Discrete In
         tegrator_Sub/Sum8 */
      SApB_DscInt1_Sum8 = SApB_DscInt1_Switch1 + SApB_DscInt1_Out_old;

      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_T
         CS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/HI13_Side
         _Slip_Angle_Estimation/Discrete Integrator/Discrete Integrator/Discrete
          Integrator_Sub/Saturation Dynamic1/Switch2
         ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV_core
         /HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_TCS_MAIN/
         TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/HI13_Side_Slip_An
         gle_Estimation/Discrete Integrator/Discrete Integrator/Discrete Integra
         tor_Sub/Saturation Dynamic1/Switch2: Omitted comparison with constant.
         # combined # Relational: ApplicationLayerBEV_ac/ApplicationLayerBEV_run
         /ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CO
         NTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_Handling
         Indices/HI13_Side_Slip_Angle_Estimation/Discrete Integrator/Discrete In
         tegrator/Discrete Integrator_Sub/Saturation Dynamic1/LowerRelop1 */
      if (SApB_DscInt1_Sum8 > SApB_DscInt1_AntiWindupMax) {
         /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLa
            yerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/T
            CS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/
            HI13_Side_Slip_Angle_Estimation/Discrete Integrator/Discrete Integra
            tor/Discrete Integrator_Sub/Saturation Dynamic1/Switch2
            # combined # Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/
            ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_
            CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_Han
            dlingIndices/HI13_Side_Slip_Angle_Estimation/Discrete Integrator/Dis
            crete Integrator/Discrete Integrator_Sub/Switch */
         SApB_DscInt1_Switch = SApB_DscInt1_AntiWindupMax;
      }
      else {
         /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLa
            yerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/T
            CS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/
            HI13_Side_Slip_Angle_Estimation/Discrete Integrator/Discrete Integra
            tor/Discrete Integrator_Sub/Saturation Dynamic1/Switch
            ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV_c
            ore/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_TCS
            _MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/HI13_Sid
            e_Slip_Angle_Estimation/Discrete Integrator/Discrete Integrator/Disc
            rete Integrator_Sub/Saturation Dynamic1/Switch: Omitted comparison w
            ith constant.
            # combined # Relational: ApplicationLayerBEV_ac/ApplicationLayerBEV_
            run/ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TOR
            QUE_CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07
            _HandlingIndices/HI13_Side_Slip_Angle_Estimation/Discrete Integrator
            /Discrete Integrator/Discrete Integrator_Sub/Saturation Dynamic1/Upp
            erRelop */
         if (SApB_DscInt1_Sum8 < SApB_DscInt1_AntiWindupMin) {
            /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Applicatio
               nLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL
               /TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_Handlin
               gIndices/HI13_Side_Slip_Angle_Estimation/Discrete Integrator/Disc
               rete Integrator/Discrete Integrator_Sub/Saturation Dynamic1/Switc
               h
               # combined # Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_r
               un/ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_T
               ORQUE_CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING
               /SP07_HandlingIndices/HI13_Side_Slip_Angle_Estimation/Discrete In
               tegrator/Discrete Integrator/Discrete Integrator_Sub/Saturation D
               ynamic1/Switch2
               # combined # Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_r
               un/ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_T
               ORQUE_CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING
               /SP07_HandlingIndices/HI13_Side_Slip_Angle_Estimation/Discrete In
               tegrator/Discrete Integrator/Discrete Integrator_Sub/Switch */
            SApB_DscInt1_Switch = SApB_DscInt1_AntiWindupMin;
         }
         else {
            /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Applicatio
               nLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL
               /TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_Handlin
               gIndices/HI13_Side_Slip_Angle_Estimation/Discrete Integrator/Disc
               rete Integrator/Discrete Integrator_Sub/Saturation Dynamic1/Switc
               h
               # combined # Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_r
               un/ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_T
               ORQUE_CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING
               /SP07_HandlingIndices/HI13_Side_Slip_Angle_Estimation/Discrete In
               tegrator/Discrete Integrator/Discrete Integrator_Sub/Saturation D
               ynamic1/Switch2
               # combined # Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_r
               un/ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_T
               ORQUE_CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING
               /SP07_HandlingIndices/HI13_Side_Slip_Angle_Estimation/Discrete In
               tegrator/Discrete Integrator/Discrete Integrator_Sub/Switch */
            SApB_DscInt1_Switch = SApB_DscInt1_Sum8;
         }
      }
   }

   /* # combined # TargetLink outport: ApplicationLayerBEV_ac/ApplicationLayerBE
      V_run/ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_
      CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingI
      ndices/HI13_Side_Slip_Angle_Estimation/Discrete Integrator/Discrete Integr
      ator/Discrete Integrator_Sub/Out */
   return SApB_DscInt1_Switch;
}

/******************************************************************************\
 ***  FUNCTION:
 ***      ApplBEV_FirstOrderLPF_Init
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      float32            SApB_LPF1IN1_In     
 ***      float32            SApB_LPF1IN1_Init   
 ***      float32            SApB_LPF1IN1_Reset  
 ***      float32            SApB_LPF1IN1_Cutoff 
 ***      float32            SApB_LPF1IN1_Out_old 
 ***
 ***  RETURNS:
 ***      float32
 ***
 ***  SETTINGS:
 ***
\******************************************************************************/
float32 ApplBEV_FirstOrderLPF_Init(float32 SApB_LPF1IN1_In, float32 SApB_LPF1IN1_Init, float32
  SApB_LPF1IN1_Reset, float32 SApB_LPF1IN1_Cutoff, float32 SApB_LPF1IN1_Out_old)
{
   float32 SApB_LPF1IN1_Switch;

   /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV
      _core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_TCS_MAI
      N/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP03_VehicleSignals/VS04_Wheels_Signals
      /VS01_Wheels_Speed/CsE03_TYRE_TOL/RTA calculation/First Order LP Filter18/
      First Order LP Filter Init/First Order LP Filter Init_Sub/Switch */
   if (SApB_LPF1IN1_Reset >= 0.5F) {
      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_T
         CS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP03_VehicleSignals/VS04_Wheel
         s_Signals/VS01_Wheels_Speed/CsE03_TYRE_TOL/RTA calculation/First Order 
         LP Filter18/First Order LP Filter Init/First Order LP Filter Init_Sub/S
         witch */
      SApB_LPF1IN1_Switch = SApB_LPF1IN1_Init;
   }
   else {
      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_T
         CS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP03_VehicleSignals/VS04_Wheel
         s_Signals/VS01_Wheels_Speed/CsE03_TYRE_TOL/RTA calculation/First Order 
         LP Filter18/First Order LP Filter Init/First Order LP Filter Init_Sub/S
         witch
         # combined # Sum: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Applic
         ationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/T
         CS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP03_VehicleSignals/
         VS04_Wheels_Signals/VS01_Wheels_Speed/CsE03_TYRE_TOL/RTA calculation/Fi
         rst Order LP Filter18/First Order LP Filter Init/First Order LP Filter 
         Init_Sub/Sum2
         # combined # Product: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Ap
         plicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTR
         OL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP03_VehicleSign
         als/VS04_Wheels_Signals/VS01_Wheels_Speed/CsE03_TYRE_TOL/RTA calculatio
         n/First Order LP Filter18/First Order LP Filter Init/First Order LP Fil
         ter Init_Sub/Product
         # combined # Sum: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Applic
         ationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/T
         CS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP03_VehicleSignals/
         VS04_Wheels_Signals/VS01_Wheels_Speed/CsE03_TYRE_TOL/RTA calculation/Fi
         rst Order LP Filter18/First Order LP Filter Init/First Order LP Filter 
         Init_Sub/Sum */
      SApB_LPF1IN1_Switch = ((SApB_LPF1IN1_In - SApB_LPF1IN1_Out_old) * SApB_LPF1IN1_Cutoff) +
       SApB_LPF1IN1_Out_old;
   }

   /* # combined # TargetLink outport: ApplicationLayerBEV_ac/ApplicationLayerBE
      V_run/ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_
      CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP03_VehicleSi
      gnals/VS04_Wheels_Signals/VS01_Wheels_Speed/CsE03_TYRE_TOL/RTA calculation
      /First Order LP Filter18/First Order LP Filter Init/First Order LP Filter 
      Init_Sub/Out */
   return SApB_LPF1IN1_Switch;
}

/******************************************************************************\
 ***  FUNCTION:
 ***      ApplBEV_FirstOrderLowPassFilter
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      float32            SApB_LPF11_In       
 ***      float32            SApB_LPF11_Cutoff   
 ***      float32            SApB_LPF11_Out_old  
 ***
 ***  RETURNS:
 ***      float32
 ***
 ***  SETTINGS:
 ***
\******************************************************************************/
float32 ApplBEV_FirstOrderLowPassFilter(float32 SApB_LPF11_In, float32 SApB_LPF11_Cutoff, float32
  SApB_LPF11_Out_old)
{
   /* # combined # TargetLink outport: ApplicationLayerBEV_ac/ApplicationLayerBE
      V_run/ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_
      CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP03_VehicleSi
      gnals/VS01_DRS_Signals/First Order LP Filter/First Order LP Filter/First O
      rder LP Filter_Sub/Out
      # combined # Sum: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Applicati
      onLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS
      02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP03_VehicleSignals/VS01_DRS_
      Signals/First Order LP Filter/First Order LP Filter/First Order LP Filter_
      Sub/Sum2
      # combined # Product: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Appli
      cationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS
      /TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP03_VehicleSignals/VS01_
      DRS_Signals/First Order LP Filter/First Order LP Filter/First Order LP Fil
      ter_Sub/Product
      # combined # Sum: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Applicati
      onLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS
      02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP03_VehicleSignals/VS01_DRS_
      Signals/First Order LP Filter/First Order LP Filter/First Order LP Filter_
      Sub/Sum */
   return ((SApB_LPF11_Cutoff * (SApB_LPF11_In - SApB_LPF11_Out_old)) + SApB_LPF11_Out_old);
}

/******************************************************************************\
 ***  FUNCTION:
 ***      ApplBEV_RateLimiter
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      float32            SApB_RatL1_In       
 ***      float32            SApB_RatL1_Rate_Up  
 ***      float32            SApB_RatL1_Rate_Down 
 ***      boolean            SApB_RatL1_DIsable_Up 
 ***      boolean            SApB_RatL1_Disable_Down 
 ***      float32            SApB_RatL1_Init     
 ***      boolean            SApB_RatL1_InitDelaySwitchEn 
 ***      float32            SApB_RatL1_Out_old  
 ***
 ***  RETURNS:
 ***      float32
 ***
 ***  SETTINGS:
 ***
\******************************************************************************/
float32 ApplBEV_RateLimiter(float32 SApB_RatL1_In, float32 SApB_RatL1_Rate_Up, float32
  SApB_RatL1_Rate_Down, boolean SApB_RatL1_DIsable_Up, boolean SApB_RatL1_Disable_Down, float32
  SApB_RatL1_Init, boolean SApB_RatL1_InitDelaySwitchEn, float32 SApB_RatL1_Out_old)
{
   float32 SApB_RatL1_Sum;
   float32 SApB_RatL1_switch1;
   float32 SApB_RatL2_Switch;

   /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV
      _core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/BatteryDriverReqSa
      turation/DriverReqRateLim/Rate Limiter/Rate Limiter_Sub/Init_delay/Switch
      ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV_core/Hi
      ghLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/BatteryDriverReqSaturation
      /DriverReqRateLim/Rate Limiter/Rate Limiter_Sub/Init_delay/Switch: Omitted
       comparison with constant. */
   if (SApB_RatL1_InitDelaySwitchEn) {
      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/BatteryDrive
         rReqSaturation/DriverReqRateLim/Rate Limiter/Rate Limiter_Sub/Init_dela
         y/Switch */
      SApB_RatL2_Switch = SApB_RatL1_Out_old;
   }
   else {
      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/BatteryDrive
         rReqSaturation/DriverReqRateLim/Rate Limiter/Rate Limiter_Sub/Init_dela
         y/Switch */
      SApB_RatL2_Switch = SApB_RatL1_Init;
   }

   /* Sum: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV_co
      re/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/BatteryDriverReqSatur
      ation/DriverReqRateLim/Rate Limiter/Rate Limiter_Sub/Sum */
   SApB_RatL1_Sum = SApB_RatL1_In - SApB_RatL2_Switch;

   /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV
      _core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/BatteryDriverReqSa
      turation/DriverReqRateLim/Rate Limiter/Rate Limiter_Sub/switch1
      ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV_core/Hi
      ghLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/BatteryDriverReqSaturation
      /DriverReqRateLim/Rate Limiter/Rate Limiter_Sub/switch1: Omitted compariso
      n with constant.
      # combined # Logical: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Appli
      cationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/Batt
      eryDriverReqSaturation/DriverReqRateLim/Rate Limiter/Rate Limiter_Sub/Logi
      cal Operator2
      # combined # Relational: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Ap
      plicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/B
      atteryDriverReqSaturation/DriverReqRateLim/Rate Limiter/Rate Limiter_Sub/R
      elational Operator1 */
   if ((SApB_RatL1_Sum >= SApB_RatL1_Rate_Down) || SApB_RatL1_Disable_Down) {
      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/BatteryDrive
         rReqSaturation/DriverReqRateLim/Rate Limiter/Rate Limiter_Sub/switch
         ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV_core
         /HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/BatteryDriverReqSatu
         ration/DriverReqRateLim/Rate Limiter/Rate Limiter_Sub/switch: Omitted c
         omparison with constant.
         # combined # Logical: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Ap
         plicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPE
         R/BatteryDriverReqSaturation/DriverReqRateLim/Rate Limiter/Rate Limiter
         _Sub/Logical Operator
         # combined # Relational: ApplicationLayerBEV_ac/ApplicationLayerBEV_run
         /ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRA
         PPER/BatteryDriverReqSaturation/DriverReqRateLim/Rate Limiter/Rate Limi
         ter_Sub/Relational Operator */
      if ((SApB_RatL1_Sum <= SApB_RatL1_Rate_Up) || SApB_RatL1_DIsable_Up) {
         /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLa
            yerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/Batter
            yDriverReqSaturation/DriverReqRateLim/Rate Limiter/Rate Limiter_Sub/
            switch
            # combined # Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/
            ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_W
            RAPPER/BatteryDriverReqSaturation/DriverReqRateLim/Rate Limiter/Rate
             Limiter_Sub/switch1 */
         SApB_RatL1_switch1 = SApB_RatL1_In;
      }
      else {
         /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLa
            yerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/Batter
            yDriverReqSaturation/DriverReqRateLim/Rate Limiter/Rate Limiter_Sub/
            switch
            # combined # Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/
            ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_W
            RAPPER/BatteryDriverReqSaturation/DriverReqRateLim/Rate Limiter/Rate
             Limiter_Sub/switch1
            # combined # Sum: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/App
            licationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAP
            PER/BatteryDriverReqSaturation/DriverReqRateLim/Rate Limiter/Rate Li
            miter_Sub/Sum1 */
         SApB_RatL1_switch1 = SApB_RatL1_Rate_Up + SApB_RatL2_Switch;
      }
   }
   else {
      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/BatteryDrive
         rReqSaturation/DriverReqRateLim/Rate Limiter/Rate Limiter_Sub/switch1
         # combined # Sum: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Applic
         ationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/Ba
         tteryDriverReqSaturation/DriverReqRateLim/Rate Limiter/Rate Limiter_Sub
         /Sum5 */
      SApB_RatL1_switch1 = SApB_RatL1_Rate_Down + SApB_RatL2_Switch;
   }

   /* # combined # TargetLink outport: ApplicationLayerBEV_ac/ApplicationLayerBE
      V_run/ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_W
      RAPPER/BatteryDriverReqSaturation/DriverReqRateLim/Rate Limiter/Rate Limit
      er_Sub/Out */
   return SApB_RatL1_switch1;
}

/******************************************************************************\
 ***  FUNCTION:
 ***      ApplBEV_RateLimiterSaturated
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      float32            SApB_RatLS1_In      
 ***      float32            SApB_RatLS1_Rate_Up 
 ***      float32            SApB_RatLS1_Rate_Down 
 ***      boolean            SApB_RatLS1_DIsable_Up 
 ***      boolean            SApB_RatLS1_Disable_Down 
 ***      float32            SApB_RatLS1_Min_Value 
 ***      float32            SApB_RatLS1_Max_Value 
 ***      float32            SApB_RatLS1_Init    
 ***      boolean            SApB_RatLS1_InitDelaySwitchEn 
 ***      float32            SApB_RatLS1_Out_old 
 ***
 ***  RETURNS:
 ***      float32
 ***
 ***  SETTINGS:
 ***
\******************************************************************************/
float32 ApplBEV_RateLimiterSaturated(float32 SApB_RatLS1_In, float32 SApB_RatLS1_Rate_Up, float32
  SApB_RatLS1_Rate_Down, boolean SApB_RatLS1_DIsable_Up, boolean SApB_RatLS1_Disable_Down, float32
  SApB_RatLS1_Min_Value, float32 SApB_RatLS1_Max_Value, float32 SApB_RatLS1_Init, boolean
  SApB_RatLS1_InitDelaySwitchEn, float32 SApB_RatLS1_Out_old)
{
   float32 SApB_RatLS1_Sum;
   float32 SApB_RatLS1_switch1;
   float32 SApB_RatLS2_Switch;
   float32 SApB_RatLS3_Switch2;

   /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV
      _core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_TCS_MAI
      N/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/HI05_Slope_Estimat
      ion/Slope/Rate Limiter4/Rate Limiter Saturated/Rate Limiter Saturated_Sub/
      Init_delay/Switch
      ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV_core/Hi
      ghLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_TCS_MAIN/TCS_MA
      IN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/HI05_Slope_Estimation/Slop
      e/Rate Limiter4/Rate Limiter Saturated/Rate Limiter Saturated_Sub/Init_del
      ay/Switch: Omitted comparison with constant. */
   if (SApB_RatLS1_InitDelaySwitchEn) {
      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_T
         CS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/HI05_Slop
         e_Estimation/Slope/Rate Limiter4/Rate Limiter Saturated/Rate Limiter Sa
         turated_Sub/Init_delay/Switch */
      SApB_RatLS2_Switch = SApB_RatLS1_Out_old;
   }
   else {
      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_T
         CS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/HI05_Slop
         e_Estimation/Slope/Rate Limiter4/Rate Limiter Saturated/Rate Limiter Sa
         turated_Sub/Init_delay/Switch */
      SApB_RatLS2_Switch = SApB_RatLS1_Init;
   }

   /* Sum: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV_co
      re/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_TCS_MAIN/T
      CS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/HI05_Slope_Estimation
      /Slope/Rate Limiter4/Rate Limiter Saturated/Rate Limiter Saturated_Sub/Sum */
   SApB_RatLS1_Sum = SApB_RatLS1_In - SApB_RatLS2_Switch;

   /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV
      _core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_TCS_MAI
      N/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/HI05_Slope_Estimat
      ion/Slope/Rate Limiter4/Rate Limiter Saturated/Rate Limiter Saturated_Sub/
      switch1
      ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV_core/Hi
      ghLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_TCS_MAIN/TCS_MA
      IN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/HI05_Slope_Estimation/Slop
      e/Rate Limiter4/Rate Limiter Saturated/Rate Limiter Saturated_Sub/switch1:
       Omitted comparison with constant.
      # combined # Logical: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Appli
      cationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS
      /TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/HI05
      _Slope_Estimation/Slope/Rate Limiter4/Rate Limiter Saturated/Rate Limiter 
      Saturated_Sub/Logical Operator2
      # combined # Relational: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Ap
      plicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/
      TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/H
      I05_Slope_Estimation/Slope/Rate Limiter4/Rate Limiter Saturated/Rate Limit
      er Saturated_Sub/Relational Operator1 */
   if ((SApB_RatLS1_Sum >= SApB_RatLS1_Rate_Down) || SApB_RatLS1_Disable_Down) {
      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_T
         CS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/HI05_Slop
         e_Estimation/Slope/Rate Limiter4/Rate Limiter Saturated/Rate Limiter Sa
         turated_Sub/switch
         ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV_core
         /HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_TCS_MAIN/
         TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/HI05_Slope_Estima
         tion/Slope/Rate Limiter4/Rate Limiter Saturated/Rate Limiter Saturated_
         Sub/switch: Omitted comparison with constant.
         # combined # Logical: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Ap
         plicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTR
         OL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingInd
         ices/HI05_Slope_Estimation/Slope/Rate Limiter4/Rate Limiter Saturated/R
         ate Limiter Saturated_Sub/Logical Operator
         # combined # Relational: ApplicationLayerBEV_ac/ApplicationLayerBEV_run
         /ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CO
         NTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_Handling
         Indices/HI05_Slope_Estimation/Slope/Rate Limiter4/Rate Limiter Saturate
         d/Rate Limiter Saturated_Sub/Relational Operator */
      if ((SApB_RatLS1_Sum <= SApB_RatLS1_Rate_Up) || SApB_RatLS1_DIsable_Up) {
         /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLa
            yerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/T
            CS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/
            HI05_Slope_Estimation/Slope/Rate Limiter4/Rate Limiter Saturated/Rat
            e Limiter Saturated_Sub/switch
            # combined # Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/
            ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_
            CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_Han
            dlingIndices/HI05_Slope_Estimation/Slope/Rate Limiter4/Rate Limiter 
            Saturated/Rate Limiter Saturated_Sub/switch1 */
         SApB_RatLS1_switch1 = SApB_RatLS1_In;
      }
      else {
         /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLa
            yerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/T
            CS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/
            HI05_Slope_Estimation/Slope/Rate Limiter4/Rate Limiter Saturated/Rat
            e Limiter Saturated_Sub/switch
            # combined # Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/
            ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_
            CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_Han
            dlingIndices/HI05_Slope_Estimation/Slope/Rate Limiter4/Rate Limiter 
            Saturated/Rate Limiter Saturated_Sub/switch1
            # combined # Sum: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/App
            licationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CON
            TROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_Handli
            ngIndices/HI05_Slope_Estimation/Slope/Rate Limiter4/Rate Limiter Sat
            urated/Rate Limiter Saturated_Sub/Sum1 */
         SApB_RatLS1_switch1 = SApB_RatLS1_Rate_Up + SApB_RatLS2_Switch;
      }
   }
   else {
      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_T
         CS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/HI05_Slop
         e_Estimation/Slope/Rate Limiter4/Rate Limiter Saturated/Rate Limiter Sa
         turated_Sub/switch1
         # combined # Sum: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Applic
         ationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/T
         CS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices
         /HI05_Slope_Estimation/Slope/Rate Limiter4/Rate Limiter Saturated/Rate 
         Limiter Saturated_Sub/Sum5 */
      SApB_RatLS1_switch1 = SApB_RatLS1_Rate_Down + SApB_RatLS2_Switch;
   }

   /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV
      _core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_TCS_MAI
      N/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/HI05_Slope_Estimat
      ion/Slope/Rate Limiter4/Rate Limiter Saturated/Rate Limiter Saturated_Sub/
      Saturation Dynamic1/Switch2
      ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV_core/Hi
      ghLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_TCS_MAIN/TCS_MA
      IN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/HI05_Slope_Estimation/Slop
      e/Rate Limiter4/Rate Limiter Saturated/Rate Limiter Saturated_Sub/Saturati
      on Dynamic1/Switch2: Omitted comparison with constant.
      # combined # Relational: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Ap
      plicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/
      TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/H
      I05_Slope_Estimation/Slope/Rate Limiter4/Rate Limiter Saturated/Rate Limit
      er Saturated_Sub/Saturation Dynamic1/LowerRelop1 */
   if (SApB_RatLS1_switch1 > SApB_RatLS1_Max_Value) {
      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_T
         CS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/HI05_Slop
         e_Estimation/Slope/Rate Limiter4/Rate Limiter Saturated/Rate Limiter Sa
         turated_Sub/Saturation Dynamic1/Switch2 */
      SApB_RatLS3_Switch2 = SApB_RatLS1_Max_Value;
   }
   else {
      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_T
         CS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/HI05_Slop
         e_Estimation/Slope/Rate Limiter4/Rate Limiter Saturated/Rate Limiter Sa
         turated_Sub/Saturation Dynamic1/Switch
         ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV_core
         /HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_TCS_MAIN/
         TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/HI05_Slope_Estima
         tion/Slope/Rate Limiter4/Rate Limiter Saturated/Rate Limiter Saturated_
         Sub/Saturation Dynamic1/Switch: Omitted comparison with constant.
         # combined # Relational: ApplicationLayerBEV_ac/ApplicationLayerBEV_run
         /ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CO
         NTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_Handling
         Indices/HI05_Slope_Estimation/Slope/Rate Limiter4/Rate Limiter Saturate
         d/Rate Limiter Saturated_Sub/Saturation Dynamic1/UpperRelop */
      if (SApB_RatLS1_switch1 < SApB_RatLS1_Min_Value) {
         /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLa
            yerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/T
            CS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/
            HI05_Slope_Estimation/Slope/Rate Limiter4/Rate Limiter Saturated/Rat
            e Limiter Saturated_Sub/Saturation Dynamic1/Switch
            # combined # Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/
            ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_
            CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_Han
            dlingIndices/HI05_Slope_Estimation/Slope/Rate Limiter4/Rate Limiter 
            Saturated/Rate Limiter Saturated_Sub/Saturation Dynamic1/Switch2 */
         SApB_RatLS3_Switch2 = SApB_RatLS1_Min_Value;
      }
      else {
         /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLa
            yerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/T
            CS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingIndices/
            HI05_Slope_Estimation/Slope/Rate Limiter4/Rate Limiter Saturated/Rat
            e Limiter Saturated_Sub/Saturation Dynamic1/Switch
            # combined # Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/
            ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_
            CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_Han
            dlingIndices/HI05_Slope_Estimation/Slope/Rate Limiter4/Rate Limiter 
            Saturated/Rate Limiter Saturated_Sub/Saturation Dynamic1/Switch2 */
         SApB_RatLS3_Switch2 = SApB_RatLS1_switch1;
      }
   }

   /* # combined # TargetLink outport: ApplicationLayerBEV_ac/ApplicationLayerBE
      V_run/ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_
      CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP07_HandlingI
      ndices/HI05_Slope_Estimation/Slope/Rate Limiter4/Rate Limiter Saturated/Ra
      te Limiter Saturated_Sub/Out */
   return SApB_RatLS3_Switch2;
}

/******************************************************************************\
 ***  FUNCTION:
 ***      ApplBEV_RateLimiterSaturationHold
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      float32            SApB_RatLSH1_In     
 ***      float32            SApB_RatLSH1_Rate_Up 
 ***      float32            SApB_RatLSH1_Rate_Down 
 ***      boolean            SApB_RatLSH1_DIsable_Up 
 ***      boolean            SApB_RatLSH1_Disable_Down 
 ***      boolean            SApB_RatLSH1_Hold   
 ***      float32            SApB_RatLSH1_Min_Value 
 ***      float32            SApB_RatLSH1_Max_Value 
 ***      float32            SApB_RatLSH1_Init   
 ***      boolean            SApB_RatLSH1_InitDelaySwitchEn 
 ***      float32            SApB_RatLSH1_Out_old 
 ***
 ***  RETURNS:
 ***      float32
 ***
 ***  SETTINGS:
 ***
\******************************************************************************/
float32 ApplBEV_RateLimiterSaturationHold(float32 SApB_RatLSH1_In, float32 SApB_RatLSH1_Rate_Up,
  float32 SApB_RatLSH1_Rate_Down, boolean SApB_RatLSH1_DIsable_Up, boolean
  SApB_RatLSH1_Disable_Down, boolean SApB_RatLSH1_Hold, float32 SApB_RatLSH1_Min_Value, float32
  SApB_RatLSH1_Max_Value, float32 SApB_RatLSH1_Init, boolean SApB_RatLSH1_InitDelaySwitchEn, float32
   SApB_RatLSH1_Out_old)
{
   float32 SApB_RatLSH1_Sum;
   float32 SApB_RatLSH1_switch3;
   float32 SApB_RatLSH2_Switch;
   float32 SApB_RatLSH3_Switch2;

   /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV
      _core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_TCS_MAI
      N/TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_GripCalculation/GRIP02_GripFinalCal
      culation/Rate Limiter Saturated & HOLD/Rate Limiter Saturated & HOLD/Rate 
      Limiter Saturated & HOLD_Sub/Init_delay/Switch
      ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV_core/Hi
      ghLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_TCS_MAIN/TCS_MA
      IN/TM03_GRIP_ESTIMATION/GRIP02_GripCalculation/GRIP02_GripFinalCalculation
      /Rate Limiter Saturated & HOLD/Rate Limiter Saturated & HOLD/Rate Limiter 
      Saturated & HOLD_Sub/Init_delay/Switch: Omitted comparison with constant.
       */
   if (SApB_RatLSH1_InitDelaySwitchEn) {
      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_T
         CS_MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_GripCalculation/GRIP02_Gri
         pFinalCalculation/Rate Limiter Saturated & HOLD/Rate Limiter Saturated 
         & HOLD/Rate Limiter Saturated & HOLD_Sub/Init_delay/Switch */
      SApB_RatLSH2_Switch = SApB_RatLSH1_Out_old;
   }
   else {
      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_T
         CS_MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_GripCalculation/GRIP02_Gri
         pFinalCalculation/Rate Limiter Saturated & HOLD/Rate Limiter Saturated 
         & HOLD/Rate Limiter Saturated & HOLD_Sub/Init_delay/Switch */
      SApB_RatLSH2_Switch = SApB_RatLSH1_Init;
   }

   /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV
      _core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_TCS_MAI
      N/TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_GripCalculation/GRIP02_GripFinalCal
      culation/Rate Limiter Saturated & HOLD/Rate Limiter Saturated & HOLD/Rate 
      Limiter Saturated & HOLD_Sub/switch3
      ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV_core/Hi
      ghLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_TCS_MAIN/TCS_MA
      IN/TM03_GRIP_ESTIMATION/GRIP02_GripCalculation/GRIP02_GripFinalCalculation
      /Rate Limiter Saturated & HOLD/Rate Limiter Saturated & HOLD/Rate Limiter 
      Saturated & HOLD_Sub/switch3: Omitted comparison with constant. */
   if (SApB_RatLSH1_Hold) {
      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_T
         CS_MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_GripCalculation/GRIP02_Gri
         pFinalCalculation/Rate Limiter Saturated & HOLD/Rate Limiter Saturated 
         & HOLD/Rate Limiter Saturated & HOLD_Sub/switch3 */
      SApB_RatLSH1_switch3 = SApB_RatLSH2_Switch;
   }
   else {
      /* Sum: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV
         _core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_TCS_
         MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_GripCalculation/GRIP02_GripFi
         nalCalculation/Rate Limiter Saturated & HOLD/Rate Limiter Saturated & H
         OLD/Rate Limiter Saturated & HOLD_Sub/Sum */
      SApB_RatLSH1_Sum = SApB_RatLSH1_In - SApB_RatLSH2_Switch;

      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_T
         CS_MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_GripCalculation/GRIP02_Gri
         pFinalCalculation/Rate Limiter Saturated & HOLD/Rate Limiter Saturated 
         & HOLD/Rate Limiter Saturated & HOLD_Sub/switch1
         ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV_core
         /HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_TCS_MAIN/
         TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_GripCalculation/GRIP02_GripFinalCa
         lculation/Rate Limiter Saturated & HOLD/Rate Limiter Saturated & HOLD/R
         ate Limiter Saturated & HOLD_Sub/switch1: Omitted comparison with const
         ant.
         # combined # Logical: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Ap
         plicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTR
         OL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_GripCalculat
         ion/GRIP02_GripFinalCalculation/Rate Limiter Saturated & HOLD/Rate Limi
         ter Saturated & HOLD/Rate Limiter Saturated & HOLD_Sub/Logical Operator
         2
         # combined # Relational: ApplicationLayerBEV_ac/ApplicationLayerBEV_run
         /ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CO
         NTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_GripCalcu
         lation/GRIP02_GripFinalCalculation/Rate Limiter Saturated & HOLD/Rate L
         imiter Saturated & HOLD/Rate Limiter Saturated & HOLD_Sub/Relational Op
         erator1 */
      if ((SApB_RatLSH1_Sum >= SApB_RatLSH1_Rate_Down) || SApB_RatLSH1_Disable_Down) {
         /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLa
            yerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/T
            CS02_TCS_MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_GripCalculation/G
            RIP02_GripFinalCalculation/Rate Limiter Saturated & HOLD/Rate Limite
            r Saturated & HOLD/Rate Limiter Saturated & HOLD_Sub/switch
            ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV_c
            ore/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_TCS
            _MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_GripCalculation/GRIP02_Gr
            ipFinalCalculation/Rate Limiter Saturated & HOLD/Rate Limiter Satura
            ted & HOLD/Rate Limiter Saturated & HOLD_Sub/switch: Omitted compari
            son with constant.
            # combined # Logical: ApplicationLayerBEV_ac/ApplicationLayerBEV_run
            /ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE
            _CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_Gri
            pCalculation/GRIP02_GripFinalCalculation/Rate Limiter Saturated & HO
            LD/Rate Limiter Saturated & HOLD/Rate Limiter Saturated & HOLD_Sub/L
            ogical Operator
            # combined # Relational: ApplicationLayerBEV_ac/ApplicationLayerBEV_
            run/ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TOR
            QUE_CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_
            GripCalculation/GRIP02_GripFinalCalculation/Rate Limiter Saturated &
             HOLD/Rate Limiter Saturated & HOLD/Rate Limiter Saturated & HOLD_Su
            b/Relational Operator */
         if ((SApB_RatLSH1_Sum <= SApB_RatLSH1_Rate_Up) || SApB_RatLSH1_DIsable_Up) {
            /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Applicatio
               nLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL
               /TCS/TCS02_TCS_MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_GripCalc
               ulation/GRIP02_GripFinalCalculation/Rate Limiter Saturated & HOLD
               /Rate Limiter Saturated & HOLD/Rate Limiter Saturated & HOLD_Sub/
               switch
               # combined # Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_r
               un/ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_T
               ORQUE_CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GR
               IP02_GripCalculation/GRIP02_GripFinalCalculation/Rate Limiter Sat
               urated & HOLD/Rate Limiter Saturated & HOLD/Rate Limiter Saturate
               d & HOLD_Sub/switch1
               # combined # Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_r
               un/ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_T
               ORQUE_CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GR
               IP02_GripCalculation/GRIP02_GripFinalCalculation/Rate Limiter Sat
               urated & HOLD/Rate Limiter Saturated & HOLD/Rate Limiter Saturate
               d & HOLD_Sub/switch3 */
            SApB_RatLSH1_switch3 = SApB_RatLSH1_In;
         }
         else {
            /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Applicatio
               nLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL
               /TCS/TCS02_TCS_MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_GripCalc
               ulation/GRIP02_GripFinalCalculation/Rate Limiter Saturated & HOLD
               /Rate Limiter Saturated & HOLD/Rate Limiter Saturated & HOLD_Sub/
               switch
               # combined # Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_r
               un/ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_T
               ORQUE_CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GR
               IP02_GripCalculation/GRIP02_GripFinalCalculation/Rate Limiter Sat
               urated & HOLD/Rate Limiter Saturated & HOLD/Rate Limiter Saturate
               d & HOLD_Sub/switch1
               # combined # Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_r
               un/ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_T
               ORQUE_CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GR
               IP02_GripCalculation/GRIP02_GripFinalCalculation/Rate Limiter Sat
               urated & HOLD/Rate Limiter Saturated & HOLD/Rate Limiter Saturate
               d & HOLD_Sub/switch3
               # combined # Sum: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/
               ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQ
               UE_CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP0
               2_GripCalculation/GRIP02_GripFinalCalculation/Rate Limiter Satura
               ted & HOLD/Rate Limiter Saturated & HOLD/Rate Limiter Saturated &
                HOLD_Sub/Sum1 */
            SApB_RatLSH1_switch3 = SApB_RatLSH1_Rate_Up + SApB_RatLSH2_Switch;
         }
      }
      else {
         /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLa
            yerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/T
            CS02_TCS_MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_GripCalculation/G
            RIP02_GripFinalCalculation/Rate Limiter Saturated & HOLD/Rate Limite
            r Saturated & HOLD/Rate Limiter Saturated & HOLD_Sub/switch1
            # combined # Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/
            ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_
            CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_Grip
            Calculation/GRIP02_GripFinalCalculation/Rate Limiter Saturated & HOL
            D/Rate Limiter Saturated & HOLD/Rate Limiter Saturated & HOLD_Sub/sw
            itch3
            # combined # Sum: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/App
            licationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CON
            TROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_GripCal
            culation/GRIP02_GripFinalCalculation/Rate Limiter Saturated & HOLD/R
            ate Limiter Saturated & HOLD/Rate Limiter Saturated & HOLD_Sub/Sum5
             */
         SApB_RatLSH1_switch3 = SApB_RatLSH1_Rate_Down + SApB_RatLSH2_Switch;
      }
   }

   /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV
      _core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_TCS_MAI
      N/TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_GripCalculation/GRIP02_GripFinalCal
      culation/Rate Limiter Saturated & HOLD/Rate Limiter Saturated & HOLD/Rate 
      Limiter Saturated & HOLD_Sub/Saturation Dynamic1/Switch2
      ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV_core/Hi
      ghLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_TCS_MAIN/TCS_MA
      IN/TM03_GRIP_ESTIMATION/GRIP02_GripCalculation/GRIP02_GripFinalCalculation
      /Rate Limiter Saturated & HOLD/Rate Limiter Saturated & HOLD/Rate Limiter 
      Saturated & HOLD_Sub/Saturation Dynamic1/Switch2: Omitted comparison with 
      constant.
      # combined # Relational: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Ap
      plicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/
      TCS/TCS02_TCS_MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_GripCalculation/GR
      IP02_GripFinalCalculation/Rate Limiter Saturated & HOLD/Rate Limiter Satur
      ated & HOLD/Rate Limiter Saturated & HOLD_Sub/Saturation Dynamic1/LowerRel
      op1 */
   if (SApB_RatLSH1_switch3 > SApB_RatLSH1_Max_Value) {
      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_T
         CS_MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_GripCalculation/GRIP02_Gri
         pFinalCalculation/Rate Limiter Saturated & HOLD/Rate Limiter Saturated 
         & HOLD/Rate Limiter Saturated & HOLD_Sub/Saturation Dynamic1/Switch2 */
      SApB_RatLSH3_Switch2 = SApB_RatLSH1_Max_Value;
   }
   else {
      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_T
         CS_MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_GripCalculation/GRIP02_Gri
         pFinalCalculation/Rate Limiter Saturated & HOLD/Rate Limiter Saturated 
         & HOLD/Rate Limiter Saturated & HOLD_Sub/Saturation Dynamic1/Switch
         ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV_core
         /HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_TCS_MAIN/
         TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_GripCalculation/GRIP02_GripFinalCa
         lculation/Rate Limiter Saturated & HOLD/Rate Limiter Saturated & HOLD/R
         ate Limiter Saturated & HOLD_Sub/Saturation Dynamic1/Switch: Omitted co
         mparison with constant.
         # combined # Relational: ApplicationLayerBEV_ac/ApplicationLayerBEV_run
         /ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CO
         NTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_GripCalcu
         lation/GRIP02_GripFinalCalculation/Rate Limiter Saturated & HOLD/Rate L
         imiter Saturated & HOLD/Rate Limiter Saturated & HOLD_Sub/Saturation Dy
         namic1/UpperRelop */
      if (SApB_RatLSH1_switch3 < SApB_RatLSH1_Min_Value) {
         /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLa
            yerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/T
            CS02_TCS_MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_GripCalculation/G
            RIP02_GripFinalCalculation/Rate Limiter Saturated & HOLD/Rate Limite
            r Saturated & HOLD/Rate Limiter Saturated & HOLD_Sub/Saturation Dyna
            mic1/Switch
            # combined # Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/
            ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_
            CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_Grip
            Calculation/GRIP02_GripFinalCalculation/Rate Limiter Saturated & HOL
            D/Rate Limiter Saturated & HOLD/Rate Limiter Saturated & HOLD_Sub/Sa
            turation Dynamic1/Switch2 */
         SApB_RatLSH3_Switch2 = SApB_RatLSH1_Min_Value;
      }
      else {
         /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLa
            yerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/T
            CS02_TCS_MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_GripCalculation/G
            RIP02_GripFinalCalculation/Rate Limiter Saturated & HOLD/Rate Limite
            r Saturated & HOLD/Rate Limiter Saturated & HOLD_Sub/Saturation Dyna
            mic1/Switch
            # combined # Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/
            ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_
            CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_Grip
            Calculation/GRIP02_GripFinalCalculation/Rate Limiter Saturated & HOL
            D/Rate Limiter Saturated & HOLD/Rate Limiter Saturated & HOLD_Sub/Sa
            turation Dynamic1/Switch2 */
         SApB_RatLSH3_Switch2 = SApB_RatLSH1_switch3;
      }
   }

   /* # combined # TargetLink outport: ApplicationLayerBEV_ac/ApplicationLayerBE
      V_run/ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_
      CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM03_GRIP_ESTIMATION/GRIP02_GripCalcul
      ation/GRIP02_GripFinalCalculation/Rate Limiter Saturated & HOLD/Rate Limit
      er Saturated & HOLD/Rate Limiter Saturated & HOLD_Sub/Out */
   return SApB_RatLSH3_Switch2;
}

/******************************************************************************\
 ***  FUNCTION:
 ***      ApplBEV_Sign
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      float32            SApB_Sign1_In       
 ***
 ***  RETURNS:
 ***      float32
 ***
 ***  SETTINGS:
 ***
\******************************************************************************/
float32 ApplBEV_Sign(float32 SApB_Sign1_In)
{
   float32 SApB_Sign1_switch;

   /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV
      _core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_TCS_MAI
      N/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP03_VehicleSignals/VS01_DRS_Signals/Si
      gn/switch
      ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV_core/Hi
      ghLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_TCS_MAIN/TCS_MA
      IN/TM02_SIGNALS_PROCESSING/SP03_VehicleSignals/VS01_DRS_Signals/Sign/switc
      h: Omitted comparison with constant.
      # combined # Relational: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Ap
      plicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/
      TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP03_VehicleSignals/VS
      01_DRS_Signals/Sign/Compare */
   if (SApB_Sign1_In >= 0.F) {
      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_T
         CS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP03_VehicleSignals/VS01_DRS_S
         ignals/Sign/switch */
      SApB_Sign1_switch = 1.F;
   }
   else {
      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_T
         CS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP03_VehicleSignals/VS01_DRS_S
         ignals/Sign/switch */
      SApB_Sign1_switch = -1.F;
   }

   /* # combined # TargetLink outport: ApplicationLayerBEV_ac/ApplicationLayerBE
      V_run/ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_
      CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM02_SIGNALS_PROCESSING/SP03_VehicleSi
      gnals/VS01_DRS_Signals/Sign/Out */
   return SApB_Sign1_switch;
}

/******************************************************************************\
 ***  FUNCTION:
 ***      ApplBEV_DebouncerSteps
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      boolean            SApB_DbcnS1_In      
 ***      boolean            SApB_DbcnS1_In_old  
 ***
 ***  RETURNS:
 ***      boolean
 ***
 ***  SETTINGS:
 ***
\******************************************************************************/
boolean ApplBEV_DebouncerSteps(boolean SApB_DbcnS1_In, boolean SApB_DbcnS1_In_old)
{
   /* # combined # TargetLink outport: ApplicationLayerBEV_ac/ApplicationLayerBE
      V_run/ApplicationLayerBEV_core/ApplicationLayerBEV_Scheduler/DiagQM_Mgm/De
      bouncer Time/Debouncer Steps/Debouncer Steps_Sublib/Out
      # combined # Logical: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Appli
      cationLayerBEV_core/ApplicationLayerBEV_Scheduler/DiagQM_Mgm/Debouncer Tim
      e/Debouncer Steps/Debouncer Steps_Sublib/Logical Operator1
      # combined # Relational: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Ap
      plicationLayerBEV_core/ApplicationLayerBEV_Scheduler/DiagQM_Mgm/Debouncer 
      Time/Debouncer Steps/Debouncer Steps_Sublib/Relational Operator1 */
   return ((SApB_DbcnS1_In == SApB_DbcnS1_In_old) && SApB_DbcnS1_In);
}

/******************************************************************************\
 ***  FUNCTION:
 ***      ApplBEV_HitCrossingFalling
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      float32            SApB_HCFall1_In     
 ***      float32            SApB_HCFall1_In_old 
 ***      float32            SApB_HCFall1_Threshold 
 ***      boolean            SApB_HCFall1_Out_old 
 ***
 ***  RETURNS:
 ***      boolean
 ***
 ***  SETTINGS:
 ***
\******************************************************************************/
boolean ApplBEV_HitCrossingFalling(float32 SApB_HCFall1_In, float32 SApB_HCFall1_In_old, float32
  SApB_HCFall1_Threshold, boolean SApB_HCFall1_Out_old)
{
   /* # combined # TargetLink outport: ApplicationLayerBEV_ac/ApplicationLayerBE
      V_run/ApplicationLayerBEV_core/DiagQM/Error_Check/Latch Time/Hit Crossing 
      Falling/Hit Crossing Falling_Sub/Out
      # combined # Logical: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Appli
      cationLayerBEV_core/DiagQM/Error_Check/Latch Time/Hit Crossing Falling/Hit
       Crossing Falling_Sub/Logical Operator
      # combined # Relational: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Ap
      plicationLayerBEV_core/DiagQM/Error_Check/Latch Time/Hit Crossing Falling/
      Hit Crossing Falling_Sub/Relational Operator2
      ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV_core/Di
      agQM/Error_Check/Latch Time/Hit Crossing Falling/Hit Crossing Falling_Sub/
      Relational Operator2: Omitted comparison with constant.
      # combined # Relational: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Ap
      plicationLayerBEV_core/DiagQM/Error_Check/Latch Time/Hit Crossing Falling/
      Hit Crossing Falling_Sub/Relational Operator
      # combined # Relational: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Ap
      plicationLayerBEV_core/DiagQM/Error_Check/Latch Time/Hit Crossing Falling/
      Hit Crossing Falling_Sub/Relational Operator1 */
   return ((SApB_HCFall1_In <= SApB_HCFall1_Threshold) && (SApB_HCFall1_In_old >
    SApB_HCFall1_Threshold) && (!(SApB_HCFall1_Out_old)));
}

/******************************************************************************\
 ***  FUNCTION:
 ***      ApplBEV_HitCrossingRising
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      float32            SApB_HCRise1_In     
 ***      float32            SApB_HCRise1_In_old 
 ***      float32            SApB_HCRise1_Threshold 
 ***      boolean            SApB_HCRise1_Out_old 
 ***
 ***  RETURNS:
 ***      boolean
 ***
 ***  SETTINGS:
 ***
\******************************************************************************/
boolean ApplBEV_HitCrossingRising(float32 SApB_HCRise1_In, float32 SApB_HCRise1_In_old, float32
  SApB_HCRise1_Threshold, boolean SApB_HCRise1_Out_old)
{
   /* # combined # TargetLink outport: ApplicationLayerBEV_ac/ApplicationLayerBE
      V_run/ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_W
      RAPPER/BatteryDriverReqSaturation/DriverReqRateLim/Hit Crossing Rising/Hit
       Crossing Rising_Sub/Out
      # combined # Logical: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Appli
      cationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/Batt
      eryDriverReqSaturation/DriverReqRateLim/Hit Crossing Rising/Hit Crossing R
      ising_Sub/Logical Operator
      # combined # Relational: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Ap
      plicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/B
      atteryDriverReqSaturation/DriverReqRateLim/Hit Crossing Rising/Hit Crossin
      g Rising_Sub/Relational Operator2
      ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV_core/Hi
      ghLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/BatteryDriverReqSaturation
      /DriverReqRateLim/Hit Crossing Rising/Hit Crossing Rising_Sub/Relational O
      perator2: Omitted comparison with constant.
      # combined # Relational: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Ap
      plicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/B
      atteryDriverReqSaturation/DriverReqRateLim/Hit Crossing Rising/Hit Crossin
      g Rising_Sub/Relational Operator
      # combined # Relational: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Ap
      plicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/B
      atteryDriverReqSaturation/DriverReqRateLim/Hit Crossing Rising/Hit Crossin
      g Rising_Sub/Relational Operator1 */
   return ((SApB_HCRise1_In > SApB_HCRise1_Threshold) && (SApB_HCRise1_In_old <=
    SApB_HCRise1_Threshold) && (!(SApB_HCRise1_Out_old)));
}

/******************************************************************************\
 ***  FUNCTION:
 ***      ApplBEV_Hold
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      float32            SApB_Hold1_Hold     
 ***      float32            SApB_Hold1_Reset    
 ***      boolean            SApB_Hold1_Out_old  
 ***
 ***  RETURNS:
 ***      boolean
 ***
 ***  SETTINGS:
 ***
\******************************************************************************/
boolean ApplBEV_Hold(float32 SApB_Hold1_Hold, float32 SApB_Hold1_Reset, boolean SApB_Hold1_Out_old)
{
   boolean SApB_Hold1_Switch1;

   /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV
      _core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_TCS_MAI
      N/TCS_MAIN/TM05_TCS_ALGORITHM/TCS04_SLIPCTRL/SC03_SLIPCTRLFRONT/TCS04_SC_P
      ID_Limits/TCS02_SC_LowerLimit/TCS01_SC_Lower_Limit_General_Reset_Condition
      s/Hold/Hold_Sub/Switch1 */
   if (SApB_Hold1_Hold >= 0.5F) {
      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_T
         CS_MAIN/TCS_MAIN/TM05_TCS_ALGORITHM/TCS04_SLIPCTRL/SC03_SLIPCTRLFRONT/T
         CS04_SC_PID_Limits/TCS02_SC_LowerLimit/TCS01_SC_Lower_Limit_General_Res
         et_Conditions/Hold/Hold_Sub/Switch1 */
      SApB_Hold1_Switch1 = 1;
   }
   else {
      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/TCS02_T
         CS_MAIN/TCS_MAIN/TM05_TCS_ALGORITHM/TCS04_SLIPCTRL/SC03_SLIPCTRLFRONT/T
         CS04_SC_PID_Limits/TCS02_SC_LowerLimit/TCS01_SC_Lower_Limit_General_Res
         et_Conditions/Hold/Hold_Sub/Switch2 */
      if (SApB_Hold1_Reset > 0.5F) {
         /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLa
            yerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/T
            CS02_TCS_MAIN/TCS_MAIN/TM05_TCS_ALGORITHM/TCS04_SLIPCTRL/SC03_SLIPCT
            RLFRONT/TCS04_SC_PID_Limits/TCS02_SC_LowerLimit/TCS01_SC_Lower_Limit
            _General_Reset_Conditions/Hold/Hold_Sub/Switch2
            # combined # Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/
            ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_
            CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM05_TCS_ALGORITHM/TCS04_SLIPCTR
            L/SC03_SLIPCTRLFRONT/TCS04_SC_PID_Limits/TCS02_SC_LowerLimit/TCS01_S
            C_Lower_Limit_General_Reset_Conditions/Hold/Hold_Sub/Switch1 */
         SApB_Hold1_Switch1 = 0;
      }
      else {
         /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLa
            yerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_CONTROL/TCS/T
            CS02_TCS_MAIN/TCS_MAIN/TM05_TCS_ALGORITHM/TCS04_SLIPCTRL/SC03_SLIPCT
            RLFRONT/TCS04_SC_PID_Limits/TCS02_SC_LowerLimit/TCS01_SC_Lower_Limit
            _General_Reset_Conditions/Hold/Hold_Sub/Switch2
            # combined # Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/
            ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_
            CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM05_TCS_ALGORITHM/TCS04_SLIPCTR
            L/SC03_SLIPCTRLFRONT/TCS04_SC_PID_Limits/TCS02_SC_LowerLimit/TCS01_S
            C_Lower_Limit_General_Reset_Conditions/Hold/Hold_Sub/Switch1 */
         SApB_Hold1_Switch1 = SApB_Hold1_Out_old;
      }
   }

   /* # combined # TargetLink outport: ApplicationLayerBEV_ac/ApplicationLayerBE
      V_run/ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_TORQUE_
      CONTROL/TCS/TCS02_TCS_MAIN/TCS_MAIN/TM05_TCS_ALGORITHM/TCS04_SLIPCTRL/SC03
      _SLIPCTRLFRONT/TCS04_SC_PID_Limits/TCS02_SC_LowerLimit/TCS01_SC_Lower_Limi
      t_General_Reset_Conditions/Hold/Hold_Sub/Out */
   return SApB_Hold1_Switch1;
}

/******************************************************************************\
 ***  FUNCTION:
 ***      ApplBEV_Relay
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      boolean            SApB_Relay1_Set     
 ***      boolean            SApB_Relay1_Reset   
 ***      boolean            SApB_Relay1_Out_old 
 ***
 ***  RETURNS:
 ***      boolean
 ***
 ***  SETTINGS:
 ***
\******************************************************************************/
boolean ApplBEV_Relay(boolean SApB_Relay1_Set, boolean SApB_Relay1_Reset, boolean
  SApB_Relay1_Out_old)
{
   boolean SApB_Relay1_Switch1;

   /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV
      _core/DiagQM/Error_Check/Relay/Relay_Sub/Switch1
      ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV_core/Di
      agQM/Error_Check/Relay/Relay_Sub/Switch1: Omitted comparison with constant
      .
      # combined # Logical: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Appli
      cationLayerBEV_core/DiagQM/Error_Check/Relay/Relay_Sub/Logical Operator
      # combined # Logical: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Appli
      cationLayerBEV_core/DiagQM/Error_Check/Relay/Relay_Sub/Logical Operator1
       */
   if (SApB_Relay1_Set && (!(SApB_Relay1_Reset))) {
      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/DiagQM/Error_Check/Relay/Relay_Sub/Switch1 */
      SApB_Relay1_Switch1 = 1;
   }
   else {
      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/DiagQM/Error_Check/Relay/Relay_Sub/Switch2
         ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV_core
         /DiagQM/Error_Check/Relay/Relay_Sub/Switch2: Omitted comparison with co
         nstant. */
      if (SApB_Relay1_Reset) {
         /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLa
            yerBEV_core/DiagQM/Error_Check/Relay/Relay_Sub/Switch2
            # combined # Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/
            ApplicationLayerBEV_core/DiagQM/Error_Check/Relay/Relay_Sub/Switch1
             */
         SApB_Relay1_Switch1 = 0;
      }
      else {
         /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLa
            yerBEV_core/DiagQM/Error_Check/Relay/Relay_Sub/Switch2
            # combined # Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/
            ApplicationLayerBEV_core/DiagQM/Error_Check/Relay/Relay_Sub/Switch1
             */
         SApB_Relay1_Switch1 = SApB_Relay1_Out_old;
      }
   }

   /* # combined # TargetLink outport: ApplicationLayerBEV_ac/ApplicationLayerBE
      V_run/ApplicationLayerBEV_core/DiagQM/Error_Check/Relay/Relay_Sub/Out */
   return SApB_Relay1_Switch1;
}

/******************************************************************************\
 ***  FUNCTION:
 ***      ApplBEV_SignalsJointManagement
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      boolean            SApB_SgnJnM1_BTestCheck 
 ***      float32            SApB_SgnJnM1_Delta_Allowed 
 ***      float32            SApB_SgnJnM1_In2    
 ***      float32            SApB_SgnJnM1_In4    
 ***      float32            SApB_SgnJnM1_Target 
 ***      float32            SApB_SgnJnM1_Current 
 ***
 ***  RETURNS:
 ***      boolean
 ***
 ***  SETTINGS:
 ***
\******************************************************************************/
boolean ApplBEV_SignalsJointManagement(boolean SApB_SgnJnM1_BTestCheck, float32
  SApB_SgnJnM1_Delta_Allowed, float32 SApB_SgnJnM1_In2, float32 SApB_SgnJnM1_In4, float32
  SApB_SgnJnM1_Target, float32 SApB_SgnJnM1_Current)
{
   float32 SApB_SgnJnM1_Switch5;

   /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV
      _core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/BatteryDriverReqSa
      turation/DriverReqRateLim/Signals Joint Management/Signals Joint Managemen
      t_sublib/Switch5
      ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV_core/Hi
      ghLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/BatteryDriverReqSaturation
      /DriverReqRateLim/Signals Joint Management/Signals Joint Management_sublib
      /Switch5: Omitted comparison with constant.
      # combined # Relational: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Ap
      plicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/B
      atteryDriverReqSaturation/DriverReqRateLim/Signals Joint Management/Signal
      s Joint Management_sublib/Relational Operator
      # combined # Abs: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Applicati
      onLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/BatteryD
      riverReqSaturation/DriverReqRateLim/Signals Joint Management/Signals Joint
       Management_sublib/Abs
      # combined # Sum: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Applicati
      onLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/BatteryD
      riverReqSaturation/DriverReqRateLim/Signals Joint Management/Signals Joint
       Management_sublib/Sum */
   if (fabsf(SApB_SgnJnM1_Target - SApB_SgnJnM1_Current) <= SApB_SgnJnM1_Delta_Allowed) {
      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/BatteryDrive
         rReqSaturation/DriverReqRateLim/Signals Joint Management/Signals Joint 
         Management_sublib/Switch5 */
      SApB_SgnJnM1_Switch5 = 1.F;
   }
   else {
      /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayer
         BEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/BatteryDrive
         rReqSaturation/DriverReqRateLim/Signals Joint Management/Signals Joint 
         Management_sublib/Switch3
         ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLayerBEV_core
         /HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/BatteryDriverReqSatu
         ration/DriverReqRateLim/Signals Joint Management/Signals Joint Manageme
         nt_sublib/Switch3: Omitted comparison with constant.
         # combined # Relational: ApplicationLayerBEV_ac/ApplicationLayerBEV_run
         /ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRA
         PPER/BatteryDriverReqSaturation/DriverReqRateLim/Signals Joint Manageme
         nt/Signals Joint Management_sublib/Relational Operator3 */
      if (SApB_SgnJnM1_In2 >= SApB_SgnJnM1_In4) {
         /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLa
            yerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/Batter
            yDriverReqSaturation/DriverReqRateLim/Signals Joint Management/Signa
            ls Joint Management_sublib/Switch3
            # combined # Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/
            ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_W
            RAPPER/BatteryDriverReqSaturation/DriverReqRateLim/Signals Joint Man
            agement/Signals Joint Management_sublib/Switch5
            # combined # Relational: ApplicationLayerBEV_ac/ApplicationLayerBEV_
            run/ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INP
            UT_WRAPPER/BatteryDriverReqSaturation/DriverReqRateLim/Signals Joint
             Management/Signals Joint Management_sublib/Relational Operator4 */
         SApB_SgnJnM1_Switch5 = (float32) (SApB_SgnJnM1_Target >= SApB_SgnJnM1_Current);
      }
      else {
         /* Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/ApplicationLa
            yerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/Batter
            yDriverReqSaturation/DriverReqRateLim/Signals Joint Management/Signa
            ls Joint Management_sublib/Switch3
            # combined # Switch: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/
            ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_W
            RAPPER/BatteryDriverReqSaturation/DriverReqRateLim/Signals Joint Man
            agement/Signals Joint Management_sublib/Switch5
            # combined # Relational: ApplicationLayerBEV_ac/ApplicationLayerBEV_
            run/ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INP
            UT_WRAPPER/BatteryDriverReqSaturation/DriverReqRateLim/Signals Joint
             Management/Signals Joint Management_sublib/Relational Operator6 */
         SApB_SgnJnM1_Switch5 = (float32) (SApB_SgnJnM1_Target <= SApB_SgnJnM1_Current);
      }
   }

   /* # combined # TargetLink outport: ApplicationLayerBEV_ac/ApplicationLayerBE
      V_run/ApplicationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_W
      RAPPER/BatteryDriverReqSaturation/DriverReqRateLim/Signals Joint Managemen
      t/Signals Joint Management_sublib/BJointFinished
      # combined # Logical: ApplicationLayerBEV_ac/ApplicationLayerBEV_run/Appli
      cationLayerBEV_core/HighLevelCtrl/VehDyn_eTM_mdl/eTM/TM_INPUT_WRAPPER/Batt
      eryDriverReqSaturation/DriverReqRateLim/Signals Joint Management/Signals J
      oint Management_sublib/Logical Operator1 */
   return (SApB_SgnJnM1_BTestCheck && (SApB_SgnJnM1_Switch5 != 0.F));
}

/*----------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/
#endif /* APPLBEV_LIBRARY_C */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
