/******************************************************************************\
 *** 
 *** Simulink model       : VDAB_SL2outBEV
 *** TargetLink subsystem : VDAB_SL2outBEV/VDAB_SL2outBEV_ac
 *** Codefile             : VDAB_Library.c
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2024-02-27 13:43:30
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : AUTOSAR
 *** AUTOSAR version                          : 4.0.3
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : disabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : enabled
 *** Exploit ranges if not erasable           : enabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : unlimited
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : disabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : disabled
 *** Inlining Threshold                       : 10
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : disabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : D:\users\valsania\Desktop\Proget
 ***                                            ti\EVCU2_Work\SWC\0AF_2402\EVCU2
 ***                                            _SWC_VDAB_SL2\MDL\VDAB_SL2outBEV
 ***                                            _s_prj\VDAB_SL2outBEV_c_prj\conf
 ***                                            ig\cconfig_AR.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLi
 ***                                            nk 4.3\Matlab\Tl\XML\CodeGen\Sty
 ***                                            lesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 4.3p5 from 18-Sep-2019
 *** Code generator version  : Build Id 4.3.0.29 from 2019-09-19 11:35:24
 *** Copyright (c) 2012 dSPACE GmbH\****************************************************************
 **************/

#ifndef VDAB_LIBRARY_C
#define VDAB_LIBRARY_C

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "VDAB_Library.h"

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/

#define CVDAB_Dsh2_START_id 1
#define CVDAB_Dsh3_RUNNING_id 2
#define CVDAB_Dsh5_START_id 1
#define CVDAB_Dsh6_RUNNING_id 2

/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INLINE FUNCTIONS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/

/******************************************************************************\
 ***  FUNCTION:
 ***      VDAB_Dsh
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      float32            SVDAB_Dsh1_Input    
 ***      float32            SVDAB_Dsh1_cut_off_freq_UP_Hz_ 
 ***      float32            SVDAB_Dsh1_cut_off_freq_DOWN__Hz_ 
 ***      float32            SVDAB_Dsh1_Init     
 ***      float32            SVDAB_Dsh1_Reset    
 ***      ISV_SVDAB_Dsh1_tp * pISV               
 ***
 ***  RETURNS:
 ***      float32
 ***
 ***  SETTINGS:
 ***
\******************************************************************************/
float32 VDAB_Dsh(float32 SVDAB_Dsh1_Input, float32 SVDAB_Dsh1_cut_off_freq_UP_Hz_, float32
  SVDAB_Dsh1_cut_off_freq_DOWN__Hz_, float32 SVDAB_Dsh1_Init, float32 SVDAB_Dsh1_Reset,
  ISV_SVDAB_Dsh1_tp * pISV)
{
   float32 SVDAB_Dsh1_Switch;
   float32 SVDAB_Dsh2_Divide;
   float32 SVDAB_Dsh2_Divide1;
   float32 SVDAB_Dsh2_Product35;
   float32 SVDAB_Dsh2_Sum;
   float32 SVDAB_Dsh2_Sum3;
   float32 SVDAB_Dsh2_Sum4;

   /* Switch: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_SL2outBEV/Driva
      bility_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monitoring_ASILAB/SAF
      ETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS01_FEED FORWARD
      /DashpotFilter/DASHPOT_filter_with_reset/Switch
      VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_SL2outBEV/Drivability_T
      ransmission_LaterlaDynamic_Monitoring/VehDyn_Monitoring_ASILAB/SAFETY_AB/S
      L2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS01_FEED FORWARD/Dashpot
      Filter/DASHPOT_filter_with_reset/Switch: Omitted comparison with constant.
      # combined # Relational: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDA
      B_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Moni
      toring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_T
      CS01_FEED FORWARD/DashpotFilter/DASHPOT_filter_with_reset/Relational Opera
      tor */
   if (SVDAB_Dsh1_Input > pISV->pISV_SVDAB_Dsh1_0_tp->X_SVDAB_Dsh1_Unit_Delay) {
      /* Switch: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_SL2outBEV/Dr
         ivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monitoring_ASIL
         AB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS01_FEE
         D FORWARD/DashpotFilter/DASHPOT_filter_with_reset/Switch */
      SVDAB_Dsh1_Switch = SVDAB_Dsh1_cut_off_freq_UP_Hz_;
   }
   else {
      /* Switch: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_SL2outBEV/Dr
         ivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monitoring_ASIL
         AB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS01_FEE
         D FORWARD/DashpotFilter/DASHPOT_filter_with_reset/Switch */
      SVDAB_Dsh1_Switch = SVDAB_Dsh1_cut_off_freq_DOWN__Hz_;
   }

   /* Product: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_SL2outBEV/Driv
      ability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monitoring_ASILAB/SA
      FETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS01_FEED FORWAR
      D/DashpotFilter/DASHPOT_filter_with_reset/Filter_width_Reset/Product35
      # combined # Product: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_S
      L2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monitor
      ing_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS0
      1_FEED FORWARD/DashpotFilter/DASHPOT_filter_with_reset/Filter_width_Reset/
      Product4
      VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_SL2outBEV/Drivability_T
      ransmission_LaterlaDynamic_Monitoring/VehDyn_Monitoring_ASILAB/SAFETY_AB/S
      L2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS01_FEED FORWARD/Dashpot
      Filter/DASHPOT_filter_with_reset/Filter_width_Reset/Product4: folded opera
      tion multiplication to constant value 0.0314159265358979 */
   SVDAB_Dsh2_Product35 = SVDAB_Dsh1_Switch * 0.031415926535897934F;

   /* Sum: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_SL2outBEV/Drivabil
      ity_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monitoring_ASILAB/SAFETY
      _AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS01_FEED FORWARD/Da
      shpotFilter/DASHPOT_filter_with_reset/Filter_width_Reset/Sum */
   SVDAB_Dsh2_Sum = SVDAB_Dsh2_Product35 + 1.F;

   /* Product: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_SL2outBEV/Driv
      ability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monitoring_ASILAB/SA
      FETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS01_FEED FORWAR
      D/DashpotFilter/DASHPOT_filter_with_reset/Filter_width_Reset/Divide */
   if (SVDAB_Dsh2_Sum != 0.F) {
      SVDAB_Dsh2_Divide = SVDAB_Dsh2_Product35 / SVDAB_Dsh2_Sum;
   }
   else {
      if (SVDAB_Dsh2_Product35 < 0.F) {
         SVDAB_Dsh2_Divide = -3.402823466e+38F;
      }
      else {
         SVDAB_Dsh2_Divide = 3.402823466e+38F;
      }
   }
   /* Begin execution of chart VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDA
      B_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Moni
      toring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_T
      CS01_FEED FORWARD/DashpotFilter/DASHPOT_filter_with_reset/Filter_width_Res
      et/delay 1/z with inizialization2/COUNTING */
   switch (pISV->pISV_SVDAB_Dsh1_2_tp->CVDAB_Dsh4_COUNTING_ns) {
      case CVDAB_Dsh5_START_id: {
         /* Begin execution of state VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_B
            EV/VDAB_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring
            /VehDyn_Monitoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_
            CALCULATION/FuSa_TCS01_FEED FORWARD/DashpotFilter/DASHPOT_filter_wit
            h_reset/Filter_width_Reset/delay 1/z with inizialization2/COUNTING.S
            TART */

         /* # combined # update of variable(s) associated with VDAB_SL2outBEV_ac
            /VDAB_SL2outBEV_run/BODY_BEV/VDAB_SL2outBEV/Drivability_Transmission
            _LaterlaDynamic_Monitoring/VehDyn_Monitoring_ASILAB/SAFETY_AB/SL2AB_
            Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS01_FEED FORWARD/Dashpo
            tFilter/DASHPOT_filter_with_reset/Reset */
         if (SVDAB_Dsh1_Reset == 0.F) {
            pISV->pISV_SVDAB_Dsh1_0_tp->CVDAB_Dsh4_out =
             pISV->pISV_SVDAB_Dsh1_0_tp->X_SVDAB_Dsh5_Unit_Delay2;

            /* State transition to VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV
               /VDAB_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitorin
               g/VehDyn_Monitoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_
               TCS_CALCULATION/FuSa_TCS01_FEED FORWARD/DashpotFilter/DASHPOT_fil
               ter_with_reset/Filter_width_Reset/delay 1/z with inizialization2/
               COUNTING.RUNNING */
            pISV->pISV_SVDAB_Dsh1_2_tp->CVDAB_Dsh4_COUNTING_ns = CVDAB_Dsh6_RUNNING_id;
         }
         else {
            /* # combined # update of variable(s) associated with VDAB_SL2outBEV
               _ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_SL2outBEV/Drivability_Transm
               ission_LaterlaDynamic_Monitoring/VehDyn_Monitoring_ASILAB/SAFETY_
               AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS01_FEED FO
               RWARD/DashpotFilter/DASHPOT_filter_with_reset/Init */
            pISV->pISV_SVDAB_Dsh1_0_tp->CVDAB_Dsh4_out = SVDAB_Dsh1_Init;
         }

         /* End execution of state VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV
            /VDAB_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/V
            ehDyn_Monitoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CA
            LCULATION/FuSa_TCS01_FEED FORWARD/DashpotFilter/DASHPOT_filter_with_
            reset/Filter_width_Reset/delay 1/z with inizialization2/COUNTING.STA
            RT */
         break;
      }
      case CVDAB_Dsh6_RUNNING_id: {
         /* Begin execution of state VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_B
            EV/VDAB_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring
            /VehDyn_Monitoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_
            CALCULATION/FuSa_TCS01_FEED FORWARD/DashpotFilter/DASHPOT_filter_wit
            h_reset/Filter_width_Reset/delay 1/z with inizialization2/COUNTING.R
            UNNING */

         /* # combined # update of variable(s) associated with VDAB_SL2outBEV_ac
            /VDAB_SL2outBEV_run/BODY_BEV/VDAB_SL2outBEV/Drivability_Transmission
            _LaterlaDynamic_Monitoring/VehDyn_Monitoring_ASILAB/SAFETY_AB/SL2AB_
            Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS01_FEED FORWARD/Dashpo
            tFilter/DASHPOT_filter_with_reset/Reset */
         if (SVDAB_Dsh1_Reset == 1.F) {
            /* State transition from VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_B
               EV/VDAB_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitor
               ing/VehDyn_Monitoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS0
               2_TCS_CALCULATION/FuSa_TCS01_FEED FORWARD/DashpotFilter/DASHPOT_f
               ilter_with_reset/Filter_width_Reset/delay 1/z with inizialization
               2/COUNTING.RUNNING to VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_B
               EV/VDAB_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitor
               ing/VehDyn_Monitoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS0
               2_TCS_CALCULATION/FuSa_TCS01_FEED FORWARD/DashpotFilter/DASHPOT_f
               ilter_with_reset/Filter_width_Reset/delay 1/z with inizialization
               2/COUNTING.START */

            /* # combined # update of variable(s) associated with VDAB_SL2outBEV
               _ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_SL2outBEV/Drivability_Transm
               ission_LaterlaDynamic_Monitoring/VehDyn_Monitoring_ASILAB/SAFETY_
               AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS01_FEED FO
               RWARD/DashpotFilter/DASHPOT_filter_with_reset/Init */
            pISV->pISV_SVDAB_Dsh1_0_tp->CVDAB_Dsh4_out = SVDAB_Dsh1_Init;
            pISV->pISV_SVDAB_Dsh1_2_tp->CVDAB_Dsh4_COUNTING_ns = CVDAB_Dsh5_START_id;
         }
         else {
            pISV->pISV_SVDAB_Dsh1_0_tp->CVDAB_Dsh4_out =
             pISV->pISV_SVDAB_Dsh1_0_tp->X_SVDAB_Dsh5_Unit_Delay2;
         }

         /* End execution of state VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV
            /VDAB_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/V
            ehDyn_Monitoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CA
            LCULATION/FuSa_TCS01_FEED FORWARD/DashpotFilter/DASHPOT_filter_with_
            reset/Filter_width_Reset/delay 1/z with inizialization2/COUNTING.RUN
            NING */
         break;
      }
      default: {
         /* State transition to VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VD
            AB_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehD
            yn_Monitoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCU
            LATION/FuSa_TCS01_FEED FORWARD/DashpotFilter/DASHPOT_filter_with_res
            et/Filter_width_Reset/delay 1/z with inizialization2/COUNTING.START */
         pISV->pISV_SVDAB_Dsh1_2_tp->CVDAB_Dsh4_COUNTING_ns = CVDAB_Dsh5_START_id;
         break;
      }
   }
   /* End execution of chart VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_
      SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monito
      ring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS
      01_FEED FORWARD/DashpotFilter/DASHPOT_filter_with_reset/Filter_width_Reset
      /delay 1/z with inizialization2/COUNTING */

   /* Unit delay: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_SL2outBEV/D
      rivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monitoring_ASILAB
      /SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS01_FEED FOR
      WARD/DashpotFilter/DASHPOT_filter_with_reset/Filter_width_Reset/delay 1__z
       with inizialization2/Unit Delay2
      # combined # Product: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_S
      L2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monitor
      ing_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS0
      1_FEED FORWARD/DashpotFilter/DASHPOT_filter_with_reset/Filter_width_Reset/
      Product1 */
   pISV->pISV_SVDAB_Dsh1_0_tp->X_SVDAB_Dsh5_Unit_Delay2 = SVDAB_Dsh1_Input;

   /* Sum: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_SL2outBEV/Drivabil
      ity_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monitoring_ASILAB/SAFETY
      _AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS01_FEED FORWARD/Da
      shpotFilter/DASHPOT_filter_with_reset/Filter_width_Reset/Sum3 */
   SVDAB_Dsh2_Sum3 = SVDAB_Dsh2_Product35 - 1.F;

   /* Sum: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_SL2outBEV/Drivabil
      ity_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monitoring_ASILAB/SAFETY
      _AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS01_FEED FORWARD/Da
      shpotFilter/DASHPOT_filter_with_reset/Filter_width_Reset/Sum4 */
   SVDAB_Dsh2_Sum4 = SVDAB_Dsh2_Product35 + 1.F;

   /* Product: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_SL2outBEV/Driv
      ability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monitoring_ASILAB/SA
      FETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS01_FEED FORWAR
      D/DashpotFilter/DASHPOT_filter_with_reset/Filter_width_Reset/Divide1 */
   if (SVDAB_Dsh2_Sum4 != 0.F) {
      SVDAB_Dsh2_Divide1 = SVDAB_Dsh2_Sum3 / SVDAB_Dsh2_Sum4;
   }
   else {
      if (SVDAB_Dsh2_Sum3 < 0.F) {
         SVDAB_Dsh2_Divide1 = -3.402823466e+38F;
      }
      else {
         SVDAB_Dsh2_Divide1 = 3.402823466e+38F;
      }
   }
   /* Begin execution of chart VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDA
      B_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Moni
      toring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_T
      CS01_FEED FORWARD/DashpotFilter/DASHPOT_filter_with_reset/Filter_width_Res
      et/delay 1/z with inizialization1/COUNTING */
   switch (pISV->pISV_SVDAB_Dsh1_2_tp->CVDAB_Dsh1_COUNTING_ns) {
      case CVDAB_Dsh2_START_id: {
         /* Begin execution of state VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_B
            EV/VDAB_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring
            /VehDyn_Monitoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_
            CALCULATION/FuSa_TCS01_FEED FORWARD/DashpotFilter/DASHPOT_filter_wit
            h_reset/Filter_width_Reset/delay 1/z with inizialization1/COUNTING.S
            TART */

         /* # combined # update of variable(s) associated with VDAB_SL2outBEV_ac
            /VDAB_SL2outBEV_run/BODY_BEV/VDAB_SL2outBEV/Drivability_Transmission
            _LaterlaDynamic_Monitoring/VehDyn_Monitoring_ASILAB/SAFETY_AB/SL2AB_
            Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS01_FEED FORWARD/Dashpo
            tFilter/DASHPOT_filter_with_reset/Reset */
         if (SVDAB_Dsh1_Reset == 0.F) {
            pISV->pISV_SVDAB_Dsh1_0_tp->CVDAB_Dsh1_out =
             pISV->pISV_SVDAB_Dsh1_0_tp->X_SVDAB_Dsh4_Unit_Delay2;

            /* State transition to VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV
               /VDAB_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitorin
               g/VehDyn_Monitoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_
               TCS_CALCULATION/FuSa_TCS01_FEED FORWARD/DashpotFilter/DASHPOT_fil
               ter_with_reset/Filter_width_Reset/delay 1/z with inizialization1/
               COUNTING.RUNNING */
            pISV->pISV_SVDAB_Dsh1_2_tp->CVDAB_Dsh1_COUNTING_ns = CVDAB_Dsh3_RUNNING_id;
         }
         else {
            /* # combined # update of variable(s) associated with VDAB_SL2outBEV
               _ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_SL2outBEV/Drivability_Transm
               ission_LaterlaDynamic_Monitoring/VehDyn_Monitoring_ASILAB/SAFETY_
               AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS01_FEED FO
               RWARD/DashpotFilter/DASHPOT_filter_with_reset/Init */
            pISV->pISV_SVDAB_Dsh1_0_tp->CVDAB_Dsh1_out = SVDAB_Dsh1_Init;
         }

         /* End execution of state VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV
            /VDAB_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/V
            ehDyn_Monitoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CA
            LCULATION/FuSa_TCS01_FEED FORWARD/DashpotFilter/DASHPOT_filter_with_
            reset/Filter_width_Reset/delay 1/z with inizialization1/COUNTING.STA
            RT */
         break;
      }
      case CVDAB_Dsh3_RUNNING_id: {
         /* Begin execution of state VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_B
            EV/VDAB_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring
            /VehDyn_Monitoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_
            CALCULATION/FuSa_TCS01_FEED FORWARD/DashpotFilter/DASHPOT_filter_wit
            h_reset/Filter_width_Reset/delay 1/z with inizialization1/COUNTING.R
            UNNING */

         /* # combined # update of variable(s) associated with VDAB_SL2outBEV_ac
            /VDAB_SL2outBEV_run/BODY_BEV/VDAB_SL2outBEV/Drivability_Transmission
            _LaterlaDynamic_Monitoring/VehDyn_Monitoring_ASILAB/SAFETY_AB/SL2AB_
            Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS01_FEED FORWARD/Dashpo
            tFilter/DASHPOT_filter_with_reset/Reset */
         if (SVDAB_Dsh1_Reset == 1.F) {
            /* State transition from VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_B
               EV/VDAB_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitor
               ing/VehDyn_Monitoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS0
               2_TCS_CALCULATION/FuSa_TCS01_FEED FORWARD/DashpotFilter/DASHPOT_f
               ilter_with_reset/Filter_width_Reset/delay 1/z with inizialization
               1/COUNTING.RUNNING to VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_B
               EV/VDAB_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitor
               ing/VehDyn_Monitoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS0
               2_TCS_CALCULATION/FuSa_TCS01_FEED FORWARD/DashpotFilter/DASHPOT_f
               ilter_with_reset/Filter_width_Reset/delay 1/z with inizialization
               1/COUNTING.START */

            /* # combined # update of variable(s) associated with VDAB_SL2outBEV
               _ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_SL2outBEV/Drivability_Transm
               ission_LaterlaDynamic_Monitoring/VehDyn_Monitoring_ASILAB/SAFETY_
               AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS01_FEED FO
               RWARD/DashpotFilter/DASHPOT_filter_with_reset/Init */
            pISV->pISV_SVDAB_Dsh1_0_tp->CVDAB_Dsh1_out = SVDAB_Dsh1_Init;
            pISV->pISV_SVDAB_Dsh1_2_tp->CVDAB_Dsh1_COUNTING_ns = CVDAB_Dsh2_START_id;
         }
         else {
            pISV->pISV_SVDAB_Dsh1_0_tp->CVDAB_Dsh1_out =
             pISV->pISV_SVDAB_Dsh1_0_tp->X_SVDAB_Dsh4_Unit_Delay2;
         }

         /* End execution of state VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV
            /VDAB_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/V
            ehDyn_Monitoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CA
            LCULATION/FuSa_TCS01_FEED FORWARD/DashpotFilter/DASHPOT_filter_with_
            reset/Filter_width_Reset/delay 1/z with inizialization1/COUNTING.RUN
            NING */
         break;
      }
      default: {
         /* State transition to VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VD
            AB_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehD
            yn_Monitoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCU
            LATION/FuSa_TCS01_FEED FORWARD/DashpotFilter/DASHPOT_filter_with_res
            et/Filter_width_Reset/delay 1/z with inizialization1/COUNTING.START */
         pISV->pISV_SVDAB_Dsh1_2_tp->CVDAB_Dsh1_COUNTING_ns = CVDAB_Dsh2_START_id;
         break;
      }
   }
   /* End execution of chart VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_
      SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monito
      ring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS
      01_FEED FORWARD/DashpotFilter/DASHPOT_filter_with_reset/Filter_width_Reset
      /delay 1/z with inizialization1/COUNTING */

   /* Sum: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_SL2outBEV/Drivabil
      ity_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monitoring_ASILAB/SAFETY
      _AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS01_FEED FORWARD/Da
      shpotFilter/DASHPOT_filter_with_reset/Filter_width_Reset/Add2
      # combined # Unit delay: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDA
      B_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Moni
      toring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_T
      CS01_FEED FORWARD/DashpotFilter/DASHPOT_filter_with_reset/Filter_width_Res
      et/delay 1__z with inizialization1/Unit Delay2
      # combined # Product: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_S
      L2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monitor
      ing_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS0
      1_FEED FORWARD/DashpotFilter/DASHPOT_filter_with_reset/Filter_width_Reset/
      Product
      # combined # Sum: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_SL2ou
      tBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monitoring_
      ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS01_FE
      ED FORWARD/DashpotFilter/DASHPOT_filter_with_reset/Filter_width_Reset/Add
      # combined # Product: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_S
      L2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monitor
      ing_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS0
      1_FEED FORWARD/DashpotFilter/DASHPOT_filter_with_reset/Filter_width_Reset/
      Product2
      # combined # Product: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_S
      L2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monitor
      ing_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS0
      1_FEED FORWARD/DashpotFilter/DASHPOT_filter_with_reset/Filter_width_Reset/
      Product3
      # combined # Product: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_S
      L2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monitor
      ing_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS0
      1_FEED FORWARD/DashpotFilter/DASHPOT_filter_with_reset/Filter_width_Reset/
      Product1 */
   pISV->pISV_SVDAB_Dsh1_0_tp->X_SVDAB_Dsh4_Unit_Delay2 = ((SVDAB_Dsh2_Divide * SVDAB_Dsh1_Input) +
    (SVDAB_Dsh2_Divide * pISV->pISV_SVDAB_Dsh1_0_tp->CVDAB_Dsh4_out)) - (SVDAB_Dsh2_Divide1 *
    pISV->pISV_SVDAB_Dsh1_0_tp->CVDAB_Dsh1_out);

   /* Switch: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_SL2outBEV/Driva
      bility_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monitoring_ASILAB/SAF
      ETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS01_FEED FORWARD
      /DashpotFilter/DASHPOT_filter_with_reset/Filter_width_Reset/IC=0/Switch */
   if (pISV->pISV_SVDAB_Dsh1_0_tp->X_SVDAB_Dsh3_Unit_Delay1 != 0.F) {
      /* Switch: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_SL2outBEV/Dr
         ivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monitoring_ASIL
         AB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS01_FEE
         D FORWARD/DashpotFilter/DASHPOT_filter_with_reset/Filter_width_Reset/IC
         =0/Switch
         # combined # Unit delay: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/
         VDAB_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehDy
         n_Monitoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATI
         ON/FuSa_TCS01_FEED FORWARD/DashpotFilter/DASHPOT_filter_with_reset/Unit
          Delay
         # combined # Unit delay: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/
         VDAB_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehDy
         n_Monitoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATI
         ON/FuSa_TCS01_FEED FORWARD/DashpotFilter/DASHPOT_filter_with_reset/Filt
         er_width_Reset/delay 1__z with inizialization1/Unit Delay2 */
      pISV->pISV_SVDAB_Dsh1_0_tp->X_SVDAB_Dsh1_Unit_Delay =
       pISV->pISV_SVDAB_Dsh1_0_tp->X_SVDAB_Dsh4_Unit_Delay2;
   }
   else {
      /* Switch: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_SL2outBEV/Dr
         ivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monitoring_ASIL
         AB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS01_FEE
         D FORWARD/DashpotFilter/DASHPOT_filter_with_reset/Filter_width_Reset/IC
         =0/Switch
         # combined # Unit delay: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/
         VDAB_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehDy
         n_Monitoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATI
         ON/FuSa_TCS01_FEED FORWARD/DashpotFilter/DASHPOT_filter_with_reset/Unit
          Delay */
      pISV->pISV_SVDAB_Dsh1_0_tp->X_SVDAB_Dsh1_Unit_Delay = 0.F;
   }

   /* Unit delay: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_SL2outBEV/D
      rivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monitoring_ASILAB
      /SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_TCS01_FEED FOR
      WARD/DashpotFilter/DASHPOT_filter_with_reset/Filter_width_Reset/IC=0/Unit 
      Delay1 */
   pISV->pISV_SVDAB_Dsh1_0_tp->X_SVDAB_Dsh3_Unit_Delay1 = 1.F;

   /* # combined # TargetLink outport: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY
      _BEV/VDAB_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/Veh
      Dyn_Monitoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATIO
      N/FuSa_TCS01_FEED FORWARD/DashpotFilter/DASHPOT_filter_with_reset/Output 
      # combined # Unit delay: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDA
      B_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Moni
      toring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS02_TCS_CALCULATION/FuSa_T
      CS01_FEED FORWARD/DashpotFilter/DASHPOT_filter_with_reset/Unit Delay */
   return pISV->pISV_SVDAB_Dsh1_0_tp->X_SVDAB_Dsh1_Unit_Delay;
}

/******************************************************************************\
 ***  FUNCTION:
 ***      VDAB_Deb
 *** 
 ***  DESCRIPTION:
 ***      
 *** 
 ***  PARAMETERS:
 ***      Type               Name                Description
 ***      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***      boolean            SVDAB_Deb1_In       
 ***      float32            SVDAB_Deb1_Time     
 ***      ISV_SVDAB_Deb1_tp * pISV               
 ***
 ***  RETURNS:
 ***      boolean
 ***
 ***  SETTINGS:
 ***
\******************************************************************************/
boolean VDAB_Deb(boolean SVDAB_Deb1_In, float32 SVDAB_Deb1_Time, ISV_SVDAB_Deb1_tp * pISV)
{
   /* Begin execution of chart VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDA
      B_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Moni
      toring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS01_CONTROL_BUS/FuSa_TCS02
      _SIGNALS PROCESSING/SP07_HandlingIndices/HI04_Mu_Split_Detection/HI02_muSp
      lit_Detection_Flag_Definition/Debouncer Steps/Debouncer Time Chart/Chart */
   if (pISV->pISV_SVDAB_Deb1_3_tp->CVDAB_Deb2_COUNT) {
      /* Begin execution of state VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/
         VDAB_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehDy
         n_Monitoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS01_CONTROL_BUS/F
         uSa_TCS02_SIGNALS PROCESSING/SP07_HandlingIndices/HI04_Mu_Split_Detecti
         on/HI02_muSplit_Detection_Flag_Definition/Debouncer Steps/Debouncer Tim
         e Chart/Chart.COUNT */

      /* # combined # Logical: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDA
         B_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_M
         onitoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS01_CONTROL_BUS/FuSa
         _TCS02_SIGNALS PROCESSING/SP07_HandlingIndices/HI04_Mu_Split_Detection/
         HI02_muSplit_Detection_Flag_Definition/Debouncer Steps/Debouncer Time C
         hart/Logical Operator
         # combined # Logical: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDA
         B_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_M
         onitoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS01_CONTROL_BUS/FuSa
         _TCS02_SIGNALS PROCESSING/SP07_HandlingIndices/HI04_Mu_Split_Detection/
         HI02_muSplit_Detection_Flag_Definition/Debouncer Steps/Debouncer Time C
         hart/Logical Operator */
      if ((SVDAB_Deb1_In != pISV->pISV_SVDAB_Deb1_2_tp->X_SVDAB_Deb1_Unit_Delay) ||
       (!(SVDAB_Deb1_In))) {
         /* State transition from VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/
            VDAB_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/Ve
            hDyn_Monitoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS01_CONTROL
            _BUS/FuSa_TCS02_SIGNALS PROCESSING/SP07_HandlingIndices/HI04_Mu_Spli
            t_Detection/HI02_muSplit_Detection_Flag_Definition/Debouncer Steps/D
            ebouncer Time Chart/Chart.COUNT to VDAB_SL2outBEV_ac/VDAB_SL2outBEV_
            run/BODY_BEV/VDAB_SL2outBEV/Drivability_Transmission_LaterlaDynamic_
            Monitoring/VehDyn_Monitoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_
            TCS01_CONTROL_BUS/FuSa_TCS02_SIGNALS PROCESSING/SP07_HandlingIndices
            /HI04_Mu_Split_Detection/HI02_muSplit_Detection_Flag_Definition/Debo
            uncer Steps/Debouncer Time Chart/Chart.COUNT */
         pISV->pISV_SVDAB_Deb1_0_tp->CVDAB_Deb1_count = 1;
      }
      else {
         /* State transition from VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/
            VDAB_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/Ve
            hDyn_Monitoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS01_CONTROL
            _BUS/FuSa_TCS02_SIGNALS PROCESSING/SP07_HandlingIndices/HI04_Mu_Spli
            t_Detection/HI02_muSplit_Detection_Flag_Definition/Debouncer Steps/D
            ebouncer Time Chart/Chart.COUNT to VDAB_SL2outBEV_ac/VDAB_SL2outBEV_
            run/BODY_BEV/VDAB_SL2outBEV/Drivability_Transmission_LaterlaDynamic_
            Monitoring/VehDyn_Monitoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_
            TCS01_CONTROL_BUS/FuSa_TCS02_SIGNALS PROCESSING/SP07_HandlingIndices
            /HI04_Mu_Split_Detection/HI02_muSplit_Detection_Flag_Definition/Debo
            uncer Steps/Debouncer Time Chart/Chart.COUNT */
         pISV->pISV_SVDAB_Deb1_0_tp->CVDAB_Deb1_count = pISV->pISV_SVDAB_Deb1_0_tp->CVDAB_Deb1_count
           + 1;
      }
      pISV->pISV_SVDAB_Deb1_3_tp->CVDAB_Deb2_COUNT = 1;
      /* End execution of state VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VD
         AB_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_
         Monitoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS01_CONTROL_BUS/FuS
         a_TCS02_SIGNALS PROCESSING/SP07_HandlingIndices/HI04_Mu_Split_Detection
         /HI02_muSplit_Detection_Flag_Definition/Debouncer Steps/Debouncer Time 
         Chart/Chart.COUNT */
   }
   else {
      /* State transition to VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_
         SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Mon
         itoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS01_CONTROL_BUS/FuSa_T
         CS02_SIGNALS PROCESSING/SP07_HandlingIndices/HI04_Mu_Split_Detection/HI
         02_muSplit_Detection_Flag_Definition/Debouncer Steps/Debouncer Time Cha
         rt/Chart.COUNT */
      pISV->pISV_SVDAB_Deb1_0_tp->CVDAB_Deb1_count = 1;
      pISV->pISV_SVDAB_Deb1_3_tp->CVDAB_Deb2_COUNT = 1;
   }
   /* End execution of chart VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_
      SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monito
      ring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS01_CONTROL_BUS/FuSa_TCS02_S
      IGNALS PROCESSING/SP07_HandlingIndices/HI04_Mu_Split_Detection/HI02_muSpli
      t_Detection_Flag_Definition/Debouncer Steps/Debouncer Time Chart/Chart */

   /* Unit delay: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_SL2outBEV/D
      rivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monitoring_ASILAB
      /SAFETY_AB/SL2AB_Moniorings/FuSa_TCS01_CONTROL_BUS/FuSa_TCS02_SIGNALS PROC
      ESSING/SP07_HandlingIndices/HI04_Mu_Split_Detection/HI02_muSplit_Detection
      _Flag_Definition/Debouncer Steps/Debouncer Time Chart/Unit Delay
      # combined # Logical: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_S
      L2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monitor
      ing_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS01_CONTROL_BUS/FuSa_TCS02_SI
      GNALS PROCESSING/SP07_HandlingIndices/HI04_Mu_Split_Detection/HI02_muSplit
      _Detection_Flag_Definition/Debouncer Steps/Debouncer Time Chart/Logical Op
      erator */
   pISV->pISV_SVDAB_Deb1_2_tp->X_SVDAB_Deb1_Unit_Delay = (float32) SVDAB_Deb1_In;

   /* # combined # TargetLink outport: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY
      _BEV/VDAB_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/Veh
      Dyn_Monitoring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS01_CONTROL_BUS/Fu
      Sa_TCS02_SIGNALS PROCESSING/SP07_HandlingIndices/HI04_Mu_Split_Detection/H
      I02_muSplit_Detection_Flag_Definition/Debouncer Steps/Debouncer Time Chart
      /Out
      # combined # Relational: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDA
      B_SL2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Moni
      toring_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS01_CONTROL_BUS/FuSa_TCS02
      _SIGNALS PROCESSING/SP07_HandlingIndices/HI04_Mu_Split_Detection/HI02_muSp
      lit_Detection_Flag_Definition/Debouncer Steps/Debouncer Time Chart/Relatio
      nal Operator2
      # combined # Product: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_S
      L2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monitor
      ing_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS01_CONTROL_BUS/FuSa_TCS02_SI
      GNALS PROCESSING/SP07_HandlingIndices/HI04_Mu_Split_Detection/HI02_muSplit
      _Detection_Flag_Definition/Debouncer Steps/Debouncer Time Chart/Product3
      # combined # Product: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_S
      L2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monitor
      ing_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS01_CONTROL_BUS/FuSa_TCS02_SI
      GNALS PROCESSING/SP07_HandlingIndices/HI04_Mu_Split_Detection/HI02_muSplit
      _Detection_Flag_Definition/Debouncer Steps/Debouncer Time Chart/Product2
      # combined # Logical: VDAB_SL2outBEV_ac/VDAB_SL2outBEV_run/BODY_BEV/VDAB_S
      L2outBEV/Drivability_Transmission_LaterlaDynamic_Monitoring/VehDyn_Monitor
      ing_ASILAB/SAFETY_AB/SL2AB_Moniorings/FuSa_TCS01_CONTROL_BUS/FuSa_TCS02_SI
      GNALS PROCESSING/SP07_HandlingIndices/HI04_Mu_Split_Detection/HI02_muSplit
      _Detection_Flag_Definition/Debouncer Steps/Debouncer Time Chart/Logical Op
      erator */
   return ((((float32) SVDAB_Deb1_In) * ((float32) pISV->pISV_SVDAB_Deb1_0_tp->CVDAB_Deb1_count)) >
    (SVDAB_Deb1_Time * 100.F));
}

/*----------------------------------------------------------------------------*\
  MODULE LOCAL FUNCTION DEFINITIONS
\*----------------------------------------------------------------------------*/
#endif /* VDAB_LIBRARY_C */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
