/******************************************************************************\
 *** 
 *** Simulink model       : VDAB_SL2outBEV
 *** TargetLink subsystem : VDAB_SL2outBEV/VDAB_SL2outBEV_ac
 *** Codefile             : VDAB_Library.h
 ***
 *** Generated by TargetLink, the dSPACE production quality code generator
 *** Generation date: 2024-02-27 13:43:30
 ***
 *** CODE GENERATOR OPTIONS:
 *** Code generation mode                     : AUTOSAR
 *** AUTOSAR version                          : 4.0.3
 *** Compiler                                 : <unknown>
 *** Target                                   : Generic
 *** ANSI-C compatible code                   : yes
 *** Code Optimization                        : enabled
 *** Constant style                           : decimal
 *** Clean code option                        : enabled
 *** Logging mode                             : Do not log anything
 *** Code Coverage                            : disabled
 *** Generate empty conditional branches      : disabled
 *** Loop unroll threshold                    : 5
 *** Shift mode                               : automatic
 *** Handle unscaled SF expr. with TL type    : disabled
 *** Assignment of conditions                 : AllBooleanOutputs 
 *** Scope reduction only to function level   : enabled
 *** Exploit ranges if not erasable           : enabled
 *** Exploit Compute Through Overflow         : optimized
 *** Linker sections                          : enabled
 *** Enable Assembler                         : disabled
 *** Variable name length                     : unlimited
 *** Use global bitfields                     : disabled
 *** Stateflow: use of bitfields              : disabled
 *** State activity encoding limit            : 5
 *** Omit zero inits in restart function      : disabled
 *** Share functions between TL subsystems    : disabled
 *** Generate 64bit functions                 : disabled
 *** Inlining Threshold                       : 10
 *** Line break limit                         : 100
 *** Target optimized boolean data type       : disabled
 *** Keep saturation elements                 : disabled
 *** Extended variable sharing                : disabled
 *** Extended lifetime optimization           : enabled
 *** Style definition file                    : D:\users\valsania\Desktop\Proget
 ***                                            ti\EVCU2_Work\SWC\0AF_2402\EVCU2
 ***                                            _SWC_VDAB_SL2\MDL\VDAB_SL2outBEV
 ***                                            _s_prj\VDAB_SL2outBEV_c_prj\conf
 ***                                            ig\cconfig_AR.xml
 *** Root style sheet                         : C:\Program Files\dSPACE TargetLi
 ***                                            nk 4.3\Matlab\Tl\XML\CodeGen\Sty
 ***                                            lesheets\TL_CSourceCodeSS.xsl
 ***
 *** TargetLink version      : 4.3p5 from 18-Sep-2019
 *** Code generator version  : Build Id 4.3.0.29 from 2019-09-19 11:35:24
 *** Copyright (c) 2012 dSPACE GmbH\****************************************************************
 **************/

#ifndef VDAB_LIBRARY_H
#define VDAB_LIBRARY_H

/*----------------------------------------------------------------------------*\
  DEFINES (OPT)
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  INCLUDES
\*----------------------------------------------------------------------------*/

#include "Rte_Type.h"

/*----------------------------------------------------------------------------*\
  ENUMS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  DEFINES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  TYPEDEFS
\*----------------------------------------------------------------------------*/


typedef struct tagISV_SVDAB_Deb1_0_tp {
   uint16 CVDAB_Deb1_count;
} ISV_SVDAB_Deb1_0_tp; /* Description: Reuse substructure */

typedef struct tagISV_SVDAB_Deb1_2_tp {
   float32 X_SVDAB_Deb1_Unit_Delay;
} ISV_SVDAB_Deb1_2_tp; /* Description: Reuse substructure */

typedef struct tagISV_SVDAB_Deb1_3_tp {
   boolean CVDAB_Deb2_COUNT;
} ISV_SVDAB_Deb1_3_tp; /* Description: Reuse substructure */

typedef struct tagISV_SVDAB_Dsh1_0_tp {
   float32 CVDAB_Dsh1_out;
   float32 CVDAB_Dsh4_out;
   float32 X_SVDAB_Dsh1_Unit_Delay;
   float32 X_SVDAB_Dsh3_Unit_Delay1;
   float32 X_SVDAB_Dsh4_Unit_Delay2;
   float32 X_SVDAB_Dsh5_Unit_Delay2;
} ISV_SVDAB_Dsh1_0_tp; /* Description: Reuse substructure */

typedef struct tagISV_SVDAB_Dsh1_2_tp {
   uint8 CVDAB_Dsh1_COUNTING_ns;
   uint8 CVDAB_Dsh4_COUNTING_ns;
} ISV_SVDAB_Dsh1_2_tp; /* Description: Reuse substructure */

typedef struct tagISV_SVDAB_Deb1_tp {
   ISV_SVDAB_Deb1_0_tp * pISV_SVDAB_Deb1_0_tp;
   ISV_SVDAB_Deb1_2_tp * pISV_SVDAB_Deb1_2_tp;
   ISV_SVDAB_Deb1_3_tp * pISV_SVDAB_Deb1_3_tp;
} ISV_SVDAB_Deb1_tp; /* Description: Reuse structure */

typedef struct tagISV_SVDAB_Dsh1_tp {
   ISV_SVDAB_Dsh1_0_tp * pISV_SVDAB_Dsh1_0_tp;
   ISV_SVDAB_Dsh1_2_tp * pISV_SVDAB_Dsh1_2_tp;
} ISV_SVDAB_Dsh1_tp; /* Description: Reuse structure */

/*----------------------------------------------------------------------------*\
  VARIABLES
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  PARAMETERIZED MACROS
\*----------------------------------------------------------------------------*/
/*----------------------------------------------------------------------------*\
  FUNCTION PROTOTYPES
\*----------------------------------------------------------------------------*/

extern float32 VDAB_Dsh(float32 SVDAB_Dsh1_Input, float32 SVDAB_Dsh1_cut_off_freq_UP_Hz_, float32
   SVDAB_Dsh1_cut_off_freq_DOWN__Hz_, float32 SVDAB_Dsh1_Init, float32 SVDAB_Dsh1_Reset,
   ISV_SVDAB_Dsh1_tp * pISV);

extern boolean VDAB_Deb(boolean SVDAB_Deb1_In, float32 SVDAB_Deb1_Time, ISV_SVDAB_Deb1_tp * pISV);

#endif /* VDAB_LIBRARY_H */
/*----------------------------------------------------------------------------*\
  END OF FILE
\*----------------------------------------------------------------------------*/
